### ISSUE TITLE
[Bug] Flickery white line at bottom of page - Firefox Nightly Android

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/fenix#10598]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1634969

(Images in Bugzilla bug)

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0

Steps to reproduce:

Open a website with a dark background colour in Firefox Nightly for Android - using Oneplus 7 Pro. OxygenOS 10.0.5 based on Android 10. Nightly version 200502 06:01

Actual results:

As I scroll down I see a flickering white line at the bottom of the screen, maybe 1 or 2 pixels high.

Expected results:

No line

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-767)

**Comment by ekager** [comment]
This sounds like a toolbar margin issue maybe?

**Comment by ekager** [comment]
Seeing a tiny 1 pixel line at the top of the screen with bottom toolbar on today's nightly. 
![Screenshot_20200512-140059](https://user-images.githubusercontent.com/25442310/81745166-2d3a0a00-9459-11ea-80f9-061ccc8119b3.png)

**Comment by Tajnymag** [comment]
@ekager having the same problem

**Comment by liuche** [comment]
Sometimes shows up after a while, not immediately, maybe after going to app switcher?

**Comment by liuche** [comment]
E2 timebox

**Comment by kglazko** [comment]
I've been able to reproduce this issue (I think- or else something similar looking) on Reddit. The difference is that when you scroll the webpage, you can actually see contents of the web page such as logos or text show up within the white bar. I'm attaching a screenshot and will continue to investigate tomorrow, but now I'm wondering if this is a web content issue of some kind..
![Screenshot_20200616-195802](https://user-images.githubusercontent.com/1676235/84850930-d69e8d80-b00d-11ea-997b-f88f8390b362.png)

**Comment by liuche** [comment]
We've added some custom behaviors on top and bottom dynamic toolbars, so this might be a side effect, and something that we're telling GV. This might be something that happens because we're telling GV the wrong value in `setVerticalClipping`.

**Comment by Mugurell** [comment]
This seems pretty bothersome though at first glance nothing stands out in code..

Trying to find a regression range got me so far that I had to use builds for FirefoxCI because locally there were issues with building off of old revisions.

I'm seeing the issue reproducing even on the oldest build available on CI (Nov 2019), even before the dynamic toolbars - https://drive.google.com/file/d/1X0zA4vVcKlFZtJ62qdf06S_-KmM2lwLn

Will investigate a bit more.

**Comment by Mugurell** [comment]
I think the white space is actually rendered by GV.
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1648079 for this.

**Comment by kglazko** [comment]
Thank you! I suspected that too :) I will make sure it is on their radar.

**Comment by michas0602** [comment]
Same problem here.

Firefox Beta 
84.0.0-beta.4 (Build #2015780083)
AC 67.0.9
GV:84.0-20201206192040
AS: 67.0.0

Need more informations? Just ask.

**Comment by Mugurell** [comment]
This is still an issue affecting both the top and bottom toolbars.

**Comment by Mugurell** [comment]
One very good observation from https://github.com/mozilla-mobile/fenix/issues/17331#issuecomment-756978717
> the issue still reproduces but only when I enable dynamic address bar. If I have address bar that does not hide when I scroll down the issue doesn't exist.

**Comment by joheiska** [comment]
Having this same issue. Using static toolbar like mentioned, or zooming in even a tiny bit, seems to remove it.

85.1.3 (Build #2015792283)
AC: 70.0.20, d282b98ef
GV: 85.0.2-20210208133944
AS: 67.2.0

**Comment by karlcow** [comment]
Another instance https://github.com/mozilla-mobile/fenix/issues/10598

**Comment by Dodgexander** [comment]
I have a similar issue, but only with stable, not with nightly. The issue is particularly bad when you scroll whilst using a video.. With video the whole screen flickers, when it happens without video playing there's just horizontal lines. The issue is also present when I use my on screen keyboard.

With keyboard not used, fixed address bar stable is fine.
With hidden address bar it happens when scrolling on stable.
With keyboard up it happens with scrolling and when typing on stable.
It seems to be triggered by any on screen movement, even happens with the cursor blinking waiting for text input or a moving advertisement on stable.

In nightly none of this happens at all.

[Here's both about:support from stable where it's](https://drive.google.com/folderview?id=15xP2-6KJHyd518zABsiuakAHeES72W6I)  broken and nightly where it works fine.


Also attached is a screenshot showing the flickering lines on this very page. 
![Screenshot_2021-07-06-04-02-00](https://user-images.githubusercontent.com/6576460/124564390-02560680-de0f-11eb-95c3-e2d81cbde33e.jpg)

**Comment by Mikaka27** [comment]
I still see it on nightly
91.0a1 (Build #2015819401)

**Comment by Mugurell** [comment]
@Dodgexander  I've created https://bugzilla.mozilla.org/show_bug.cgi?id=1719280 for the issue you are seeing.
Please follow the discussion there.
If you could also post there a video of the issue it would probably help a lot.

**Comment by Dodgexander** [comment]
Thank you @Mugurell sorry for hijacking the other issue.
This bug is happening only on stable, nightly doesn't have the problem. In my testing the horizontal lines can appear with white, not just black web pages.
Flicker in video is also regardless of page theme.
The flicker when typing however only happen with dark backgrounds. 
Here's a video of all 3:
https://streamable.com/q6nmsx

**Comment by Nickoriginal** [comment]
Hello! _Not reproducible_ in Firefox 90.1.1 on:
**Samsung Galaxy A20s** (Android 10)
@Mugurell, your [bug 1719280](https://bugzilla.mozilla.org/show_bug.cgi?id=1719280) and main [bug 1696905](https://bugzilla.mozilla.org/show_bug.cgi?id=1696905) both were resolved amd closed. We can close this GitHub issue too?

**Comment by Tajnymag** [comment]
@Nickoriginal, I don't think it can be closed. It's still reproducable on Firefoxu Nigthly 91.0a1 (Build #2015821707) on OnePlus 7T/Android 11.

![Screenshot_20210713-132738.jpg](https://user-images.githubusercontent.com/3985946/125444431-ae5627c0-f41a-49e4-9e77-bb9aa695b859.jpg)

**Comment by Nickoriginal** [comment]
Yes, it is not reproducible in GitHub (where I tested this), but on other sites it still exists. Confirmed in Firefox 90.1.1, 90.0.0-beta.6 and Nightly 91.0a1 2021-07-12T17:08:00.346
<img src = https://user-images.githubusercontent.com/85299944/125445306-15fc8c84-b36a-4436-8128-d46fda5bb82a.jpg width = 45%>
<img src = https://user-images.githubusercontent.com/85299944/125445327-2406997c-ff82-4dc3-ab92-f2122378b495.jpg width = 45%>

**Comment by joheiska** [comment]
Still there and shouldnt be closed, nightly 91.0a1 on Xiaomi Mi 9T pro.

**Comment by Tajnymag** [comment]
@Nickoriginal

I can even reproduce it on Github

![Screenshot_20210713-134252.jpg](https://user-images.githubusercontent.com/3985946/125446134-9b706a6a-bf57-4d07-9e84-6fec5972177a.jpg)

**Comment by Mikaka27** [comment]
I can reproduce on github too, if you have dark mode enabled you won't see white line, instead if you look very closely you can see that as you scroll up/down, the fixed top header of github page is moving slightly up and down.

**Comment by Mugurell** [comment]
> Hello! ~_Not reproducible_ in Firefox 90.1.1 on: **Samsung Galaxy A20s** (Android 10)~
> @Mugurell, your [[bug 1719280](https://bugzilla.mozilla.org/show_bug.cgi?id=1719280)](https://bugzilla.mozilla.org/show_bug.cgi?id=1719280) and main [[bug 1696905](https://bugzilla.mozilla.org/show_bug.cgi?id=1696905)](https://bugzilla.mozilla.org/show_bug.cgi?id=1696905) both were resolved and closed (second - fixed). We should close this GitHub issue too?

That was a different issue than the one from this ticket.

For this issue there are other Bugzilla tickets open, like
https://bugzilla.mozilla.org/show_bug.cgi?id=1654632
https://bugzilla.mozilla.org/show_bug.cgi?id=1648079
The issue quite tricky to identify and solve.

**Comment by Mugurell** [comment]
Removing this from our sprint since we depend on GeckoView for a fix.

**Comment by SeburoSUMO** [comment]
User feedback - https://support.mozilla.org/en-US/questions/1350017

**Comment by Tajnymag** [comment]
Any updates? The issue is still present in the latest Nightly.

![Screenshot_20211114-191510.jpg](https://user-images.githubusercontent.com/3985946/141693400-44c1f0d0-d506-45d5-9a53-0ca04a3d492c.jpg)

**Comment by Mugurell** [comment]
I think this was resolved by https://bugzilla.mozilla.org/show_bug.cgi?id=1734261 and the fix should be available in nightly and beta.
Closing the ticket as `fixed` instead of `wontfix`.
If the problems persists this can be reopened for more investigation.
