### ISSUE TITLE
FNX2-15219 ⁃ [Bug] Failed to query installed add-ons

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12399]
## Steps to reproduce
After last nightly update i am getting an error in addon page. Failed to query add-ons

### Expected behavior
It should show the add ons

### Actual behavior
Failed to query add ons

### Device information
* Android device: ? A10
* Fenix version: ? latest nightly 

![Screenshot](https://user-images.githubusercontent.com/58127841/86971708-2bdb4400-c161-11ea-80c2-f2a1c159554d.jpg)UNITO-UNDERSCORE!20200709-025104!

**Comment by sheikh-azharuddin** [comment]
@cadeyrn

**Comment by cadeyrn** [comment]
@sheikh-azharuddin Please do not mention me for no reason. I have nothing to do with the issue and can't help.

**Comment by sheikh-azharuddin** [comment]
Developers listen to you.... Thats why i mentioned you
One more thing you have nothing to do why do you care to reply on every thread/issue

**Comment by cadeyrn** [comment]
> Developers listen to you.... Thats why i mentioned you

They listen to me as they listen to every other user. And as every other user I can only share my opinions, I can't influence any decision or accelerate the fixing of a bug. If there is a bug, they will fix it. But I can't even reproduce the issue.

> One more thing you have nothing to do why do you care to reply on every thread/issue

Not even close…

I have nothing to do with _this_ issue. And the only reason I commented here is that you mentioned me. So I had to clarify (again) that I can't do anything for you. I am user, not a developer of this product. Of course I comment on other issues when I have an opinion about something. But I can't have an opinion about something that does not affect me.

**Comment by Scripterr** [comment]
@sheikh-azharuddin I can reproduce the bug on latest nightly certainly. But it's not right to assume that developers are ignoring or not responding to the issue, your bug report don't even passed a day to say this. And not every bug report is personally send to the developers phone, and they don't always have to work and plus also have life outside github and coding. You can see if you have subscribed to the repo that the work is completely halted so they having life outside the work doing their daily routine.
Yes this is a big issue and the developer working on add-on or QA will notice the issue and prioritise work accordingly. So the best thing would be wait for a response 😊 before tagging any members.

**Comment by sheikh-azharuddin** [comment]
I understand that... But see from my viewpoint... This add on thing is a critical issue.. Yes there are other issues like browser crash when opening from custom tab which is manageable but this thing cannot be... The reason I tagged because this bug came in yesterday's build but they didn't fix and today one more version was released with same bug.... So wondering do developers really go through the basic features after build is complete...

**Comment by LittleAngelwings** [comment]
I can reproduce this also...

**Comment by hwinnemoe** [comment]
[copied from [12420](https://github.com/mozilla-mobile/fenix/issues/12420#issuecomment-656050481)]

I can reproduce on the same Nightly version, device is a Xperia Z2 on Android 6.0.1. My add-ons are still working but I cannot access them. **It still worked on yesterday's Nightly (200708)** so the regression range should be in this period.

**Comment by sheikh-azharuddin** [comment]
@hwinnemoe no worries take your time... Atleast someone from Dev team acknowledged that is enough for me... And acknowledged means soon to be fixed 😉

**Comment by Dunexus** [comment]
Please don't forget that nighly builds can be unstable, if such errors are a blocker for you, you should install beta or release versions alongside nighly and use them as primary browser to be safe.

**Comment by Amejia481** [comment]
👋  I'm trying to figured out what it the pattern to reproduce the issue. So far that I have found in common on people that are able to reproduce it's running Android 6.0.1, does anyone is able to reproduce with other OS version?  Thanks in advance.

**Comment by lnicola** [comment]
I see it on Android 10.

**Comment by Amejia481** [comment]
Thanks @lnicola

**Comment by lnicola** [comment]
Are there any logs I could check (e.g. adb logcat)?

**Comment by Amejia481** [comment]
If you could post the logs from when the issue is happening it would be pretty helpful.

**Comment by csadilek** [comment]
Removing QA needed, I can reproduce on my device and see the problem. We're getting an error when querying installed extensions via GeckoView:

```
2020-07-09 10:10:40.691 18012-18012/? E/mozac-webextensions: Failed to query installed extensions
    java.lang.Exception: Unexpected error: TypeError: can't access property "hasPermission", extension is undefined
        at org.mozilla.geckoview.CallbackResult.sendError(CallbackResult.java:2)
        at org.mozilla.gecko.EventDispatcher$JavaCallbackDelegate$1.run(EventDispatcher.java:3)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

We'll track down the cause.

**Comment by AndiAJ** [comment]
Indeed, reproducible on the latest **`Firefox Nightly 200709 from 7/9`** using a Gogle Pixel 3a (Android 10)

► Video
![20200709-172218](https://user-images.githubusercontent.com/51314259/87052245-394c0900-c209-11ea-9494-57a696404d2b.gif)

**Comment by csadilek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1651697

**Comment by LittleAngelwings** [comment]
FYI... I have this issue on Samsung Galaxy Tab A6 SM-T580 with Android 8.1.0 and also on my phone Huawei P Smart (2018) with Android 9.1.0.

**Comment by sheikh-azharuddin** [comment]
This is fixed now in latest build...👍

**Comment by csadilek** [comment]
Unfortunately, there's a caching issue involved here so this can re-appear in Nightly until https://bugzilla.mozilla.org/show_bug.cgi?id=1651697 is fixed. We're working on it.

**Comment by quadriflax** [comment]
Just chiming in, can recreate everty time on my Moto G5+ with Android 8.1. Just started with the latest version:

Nightly 200709 06:10 (Build #21910618)
AC: 50.0.20200708130551, 8ce4bdb18
GV: 80.0a1-20200707094747
AS: 61.0.7

This effectively kills my Nightly because I had NoScript installed and now I can't whiteist new sites because I can't access the setting to allow or disable.

**Comment by sheikh-azharuddin** [comment]
> Just chiming in, can recreate everty time on my Moto G5+ with Android 8.1. Just started with the latest version:
> 
> Nightly 200709 06:10 (Build #21910618)
> AC: 50.0.20200708130551, 8ce4bdb18
> GV: 80.0a1-20200707094747
> AS: 61.0.7
> 
Use the latest version and check once. It is fixed. 
200709 18:00
https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.production/latest.

**Comment by sheikh-azharuddin** [comment]
Issue popped up again in today's build
Nightly 200710 06:01 (Build #21920613)

**Comment by paritosh9199** [comment]
Same issue again on Nightly 200710 
Device: Oneplus 7 (Android 10)

**Comment by LittleAngelwings** [comment]
No problems with this nightly via Play Store

Nightly 200711 06:00 (Build #21930608)
AC: 50.0.20200710130140, b54541be1
GV: 80.0a1-20200709093347
AS: 61.0.7

**Comment by LittleAngelwings** [comment]
OK, on the latest build from FirefoxCI the issue is back

Nightly 200711 18:01 (Build #21931809)
AC: 50.0.20200710130140, b54541be1
GV: 80.0a1-20200709093347
AS: 61.0.7

**Comment by cadeyrn** [comment]
There was no fix yet and as said in a previous comment: "there's a caching issue involved" - that's why it sometimes happens and sometimes not.

**Comment by TEWatson** [comment]
Similar to @quadriflax, this disallows me from whitelisting sites since I had NoScript installed, so Nightly is unusable for me for most new sites.

Pixel 3a, Android 10
Nightly 200716 16:22 (Build #21980630)
AC: 50.0.20200712190143, 22f032ca7
GV: 80.0a1-20200711092223
AS: 61.0.7

**Comment by andreicristianpetcu** [comment]
This is fixed for me now

**Comment by andreicristianpetcu** [comment]
strange. I updated and it's broken again.

**Comment by quadriflax** [comment]
> This is fixed for me now



> strange. I updated and it's broken again.

Read above. There is a bug where this can happen on and off. It's not fixed yet. What works now may break again then work, then break, etc, until they fix this bug.

**Comment by Rob--W** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1651838 has landed in Nightly, so the immediate trigger for this bug has been fixed.

@agi90 Can this bug be closed now? If QA wants to verify the fix, the STR are at https://bugzilla.mozilla.org/show_bug.cgi?id=1651838#c2

**Comment by csadilek** [comment]
@Rob--W the fix will land in the next Fenix Nightly (tomorrow morning EST). The we can ask QA to verify :).

**Comment by csadilek** [comment]
Ok, a new version is currently rolling out that has the fix: Nightly 200721 13:47.

**Comment by AndiAJ** [comment]
Hi @csadilek , I've just re-checked this matter using the following devices: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️ Performed the following updates and everything seems to be working properly  

**`Nightly 200721 GV: 80.0a1-20200720094507`**
                              **⇓**
**`Nightly 200722 GV: 80.0a1-20200721094241`**
                              **⇓**
**`Nightly 200723 GV: 80.0a1-20200722094100`**
                              **⇓**
**`Nightly 200724 GV: 80.0a1-20200722094100`**
                              **⇓**
**`Nightly 200725 GV: 80.0a1-20200723095657`**
                              **⇓**
**`Nightly 200726 GV: 80.0a1-20200724093206`**
                              **⇓**
**`Nightly 200727 GV: 80.0a1-20200724093206`**
                              **⇓**
**`Nightly 200728 GV: 80.0a1-20200724093206`**

✔️ No errors found after using @Rob--W 's [STR](https://bugzilla.mozilla.org/show_bug.cgi?id=1651838#c2)

**Comment by agi90** [comment]
🥳

**Comment by quadriflax** [comment]
Latest nightly is bringing this problem back.

Nightly 200929 05:08 (Build #2015766697)
AC: 61.0.20200925190057, 01306f87c
GV: 83.0a1-20200922094538
AS: 63.0.0

**Comment by dhowe** [comment]
I still see this error:

Nightly 90.0a1 (Build #2015810571)
AC: 90.0.20210514190120, 33cfc2be8
GV: 90.0a1-20210514094222
AS: 76.0.0
Android 10

**Comment by cadeyrn** [comment]
> not sure why this is closed

It was closed because the issue that existed and affected every user was fixed last year (!). If you still have problems then it has nothing to do with this report and you should open a new one.

**Comment by dhowe** [comment]
> FWIW, I can't reproduce the issue.
Add a space to the name of your collection

**Comment by cadeyrn** [comment]
That's why I said that it's not related to this issue. This issue was not about collections, it was about a bug in GeckoView that affected users of the default add-ons. 😉

**Comment by dhowe** [comment]
And where does one find this issue?

**Comment by quadriflax** [comment]
I'm getting this error again with latest nightly. Tried removing collections, still can't load addons.

92.0a1 (Build #2015826121)
AC: 92.0.20210804145319, 1efe95ff30
GV: 92.0a1-20210804093931
AS: 81.0.1

Android 11

**Comment by x2k13** [comment]
> I'm getting this error again with latest nightly. Tried removing collections, still can't load addons.
> 
> 92.0a1 (Build #2015826121)
> AC: 92.0.20210804145319, 1efe95ff30
> GV: 92.0a1-20210804093931
> AS: 81.0.1
> 
> Android 11

I can confirm, same on my end only after the last update, same build you have this issues with:
92.0a1 (Build #2015826121)
AC: 92.0.20210804145319, 1efe95ff30
GV: 92.0a1-20210804093931
AS: 81.0.1
