### ISSUE TITLE
[Bug] Pages stop loading after minutes of use (device-specific?)

### ISSUE THREAD

**Issue by Sobsz** [mozilla-mobile/fenix#14023]
## Steps to reproduce
1. Have the same phone as me? I guess?
~~2. Install one of the recommended add-ons (tested: `Decentraleyes`, `HTTPS Everywhere`, `Search by Image`).~~ Turns out it happens without add-ons, too.
3. Browse the internet for a while.

### Expected behavior
Pages load as expected.

### Actual behavior
Pages crash often and early, including simple ones like DuckDuckGo [EDIT: DuckDuckGo actually crashes exceptionally often, other sites only crash about 20% of the time]. After a while, all pages in all tabs get stuck loading. Changing the URL doesn't update the address bar, but does initiate a new request in remote debugging; the request never gets anywhere though, and all the request details say "No [headers|cookies|...] for this request". This situation continues until a force quit.

### Device information
* Android device: Xiaomi Redmi 3S Prime (Android 6.0.1, 3GB RAM, MIUI Global 10.2.2.0(MALMIXM)
* Fenix version: 79.0.5

Crash logs (first and last before freeze, add-on is `Search by Image`):
https://crash-stats.mozilla.org/report/index/bp-5cb12e4a-eced-4435-a69c-495010200821
https://crash-stats.mozilla.org/report/index/bp-77f4f873-e464-4a32-8b7b-1dd640200821

**Comment by Sobsz** [comment]
Seems I've misjudged the issue, as I've removed the addons (even disabled tracking protection) and it's still happening. Probably something device-specific then?

**Comment by hwinnemoe** [comment]
Can you reproduce on Nightly? https://play.google.com/store/apps/details?id=org.mozilla.fenix

**Comment by Sobsz** [comment]
Nightly build #2015759795 crashes the whole browser before I can get to the point of not loading. At least that means I have some logs to share (not sure if related though):
- neocities.org, page crash: https://crash-stats.mozilla.org/report/index/bp-32d105fb-f80a-49d8-9f26-2dfba0200824
- neocities.org, browser crash: https://crash-stats.mozilla.org/report/index/bp-d907c509-cbe8-4d72-adf0-ec0e40200824 https://crash-stats.mozilla.org/report/index/bp-125b0ce6-f04d-4286-89b6-bd4360200824 https://crash-stats.mozilla.org/report/index/bp-f3deb480-2d26-498d-843d-0541c0200824 (multiple links probably because I tapped "Restart Firefox" thrice (sorry u.u), pasting all just in case it's for a different reason)
- mozilla.org, browser crash: https://crash-stats.mozilla.org/report/index/bp-4e5ce03f-214d-4b4b-a99d-f75400200824 (this one got stuck on loading for a sec before crashing so maybe it's related?????)

**Comment by hwinnemoe** [comment]
Thank you, that helps a lot!

**Comment by flixha** [comment]
> Seems I've misjudged the issue, as I've removed the addons (even disabled tracking protection) and it's still happening. Probably something device-specific then?

I have similarly regular crashes of tabs, and pages often stop loading after some browsing. Sometimes pages appear to load fine and crash after a few seconds. Restarting firefox can work around some of the page-load-freezes, but not all. Clearing all firefox data usually does the trick for a bit, until the crashes reappear. I'm on a Blackberry Priv STV100-4 with Android 6.0.1.

**Comment by hwinnemoe** [comment]
@flixha Can you please add the links to your crash reports and your used Fenix version here? You can find the version under _Settings_, _About Firefox_, the crashes are in _Settings_, _About Firefox_, _Crashes_.

**Comment by flixha** [comment]
> @flixha Can you please add the links to your crash reports and your used Fenix version here? You can find the version under _Settings_, _About Firefox_, the crashes are in _Settings_, _About Firefox_, _Crashes_.

Yes of course! I had downgraded to 69.0.11 in the meantime, so I needed a bit of time to upgrade again and get some new crash reports as the old ones had been deleted.
Here are 3 crash reports:
https://crash-stats.mozilla.org/report/index/bp-7d8fa60c-8a66-4a51-91a1-ac34c0200825

https://crash-stats.mozilla.org/report/index/bp-3ea486d1-6ae2-452e-95e9-9dc2e0200825

https://crash-stats.mozilla.org/report/index/bp-0dd6a1fe-2b26-4750-aa0d-ac8f70200826

When tabs stop loading (bar is at 20 %, but nothing displays), that doesn't produce any crash reports of course. So let me know if there's some other debug information that I can get for those cases.

**Comment by kbrosnan** [comment]
Those crashes should be fixed on [version 80](https://bugzilla.mozilla.org/show_bug.cgi?id=1325918). If you try [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) are you able to use that version without crashing

**Comment by flixha** [comment]
> Those crashes should be fixed on [version 80](https://bugzilla.mozilla.org/show_bug.cgi?id=1325918). If you try [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) are you able to use that version without crashing

Thanks for your quick reply. I have used Firefox Beta a bit and it's true that this very bug hasn't appeared there yet. I'm not sure whether it's been a very representative test, because also in the Beta, a lot of pages do not load (i.e., issue as described in this thread), so I'm not getting to test too many web pages.

**Comment by hwinnemoe** [comment]
Thank you :) Can you also, if possible, [try the Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). That would help to further narrow down the issue.

**Comment by hwinnemoe** [comment]
Now that Fenix Release has moved to 80.1.2/80.1.3, are you still experiencing the loading issues?

**Comment by Sobsz** [comment]
(Forgot to reply, sorry!) The main problem of "nothing loads anymore" still occurs, but pages don't seem to crash anymore (unless it auto-reloads on a crash and doesn't save a report).

**Comment by hwinnemoe** [comment]
Thanks :) what about the [Beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta), do you also still experience the loading issue there?

**Comment by flixha** [comment]
Sorry for the delay here's some info on a few test in Nightly (I had tested Beta beforeN see above).

In Nightly, I think that after using it some I still haven't gotten the same behavior where firefox is stuck loading the tab. But it feels that instead I get a lot of crashes that mostly restart Firefox, and sometimes only the tab. I'd estimate about 10-20 % of page loads generate a crash.

Here are some crash reports:
https://crash-stats.mozilla.org/report/index/ef72b444-92ca-45e1-8abc-d0e110200911

https://crash-stats.mozilla.org/report/index/bp-3d8966a3-c270-4902-98e2-25ce10200911

06a79d13-d4ad-45b9-8236-6ce73ef8d94b

2b7b7c36-9f20-48d6-ae00-f13c81a9613

55c9371a-858f-4524-b8f4-6d071508d05c

https://crash-stats.mozilla.org/report/index/bp-93d1b25b-4a78-4d9f-9139-ce5240200829

https://crash-stats.mozilla.org/report/index/bp-dd5c6eda-00a4-464f-87e8-8f1320200827

https://crash-stats.mozilla.org/report/index/bp-66dd61bd-ee7b-4f5f-b7d8-a3cdc0200827

**Comment by hwinnemoe** [comment]
@flixha Thank you! Those Nightly crashes are tracked by BZ-1660826 and are currently being worked on.

Does the [Beta ](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) now work for you? It has been updated since the last time you've tested it.

**Comment by hwinnemoe** [comment]
> 
> 
> @flixha Thank you! Those Nightly crashes are tracked by [BZ-1660826](https://bugzilla.mozilla.org/show_bug.cgi?id=1660826) and are currently being worked on.

The fix for this should have landed in Nightly since Nightly 200916 06:01. @flixha @Sobsz Are you still experiencing crashes in your Nightly version and can you still reproduce the page loading issue?

**Comment by Sobsz** [comment]
Apologies for the delay, but yes, the page-loading issue is still present. Nightly doesn't seem to crash anymore (which is an unrelated issue IMO anyway), nor does it stop loading pages, though I suspect the latter is because I only have a dozen tabs open there (vs hundreds in the main browser).
Actually, is there a way to automatically open a bunch of tabs? I tried a website that promised to do so, but it seems Firefox requires you to have the tab focused for it to open other tabs, which makes it a long-winded process of going back to the tab every time (plus it only allows two tab-openings at once, one normal and one "do you want to let this site open a pop-up").

**Comment by hwinnemoe** [comment]
@Sobsz Yes, the Nightly crashes may be unrelated, but thanks for confirming that the crashes have stopped.

@kbrosnan I think the tags for this bug should be changed to `Feature:Browsing`? I have also seen #15074 which might be a duplicate of this issue here. It is also an ARM64 device on Android 6 like the devices mentioned here.

**Comment by Sobsz** [comment]
Quote from #15074: 
> At this time another tabs can be loaded without any problems.
The bug I'm describing is browser-wide, in that no tabs will load until an app restart. Might still be related though, who knows?

**Comment by Sobsz** [comment]
Bug seems to be gone as of 82.1.3 (the fix probably appeared earlier, but I wasn't sure if it was a fluke or not).

**Comment by hwinnemoe** [comment]
@flixha Can you still reproduce on 82.1.3?
