### ISSUE TITLE
[Bug] Can't toggle off Suggested Logins 

### ISSUE THREAD

**Issue by NJTH317** [mozilla-mobile/fenix#16288]
I'm using a Galaxy S8 Active (Android), Firefox 82.1.1. Android version 9, and have Norton 360/Lifelock installed. I'm not using the Fenix beta.

I noticed a few days ago that When I went to any site that I've stored a password etc for, I wasn't asked for the old "Master (now "Primary") Password". Instead, when I tapped on "password" a purple "suggested logins" displayed, and below that, the stored username and password for the site. Obviously, this is not secure - if my phone was stolen, the consequences of access to stored credentials could be devastating.

I went to "settings > "Logins and passwords" but no triple dot option. More research produced all the info on "Lockwise", which I installed. I'm using the fingerprint sensor to unlock. That part works.

I expected that once Lockwise was installed and working, I would be asked to unlock my individual site credentials via Lockwise.

However, EVEN WHEN LOCKWISE IS LOCKED I can still get the password etc. as I described above: go to a website where I've stored a user/password, tap on either "user" or "password", and get TWO responses:  1. "Unlock Firefox Lockwise", then, below that, 2. "suggested logins" with the user/password info that should be protected by Lockwise below that. I've attached a screenshot (without my credentials, but they're there).

So Lockwise kicks in, but there's a parallel option that bypasses Lockwise.

I tried uninstalling/reinstalling Firefox.

In the Firefox "settings" > "logins and passwords" there's still no triple dots (I realize this may now be unnecessary, because of Lockwise). When I tap on "Saved logins" it tells me to "Unlock to view your saved logins" BUT I still have access to them on the individual sites.

![Screenshot](https://user-images.githubusercontent.com/73712279/97734671-b5a77800-1a96-11eb-8cf4-1a1bf359445b.jpg)

**Comment by ekager** [comment]
I'm not sure I fully understand the issue. 

Lockwise is an entirely separate app from Fenix. It is true they both use FxA sync to sync passwords across devices. 

Fenix no longer has a master password. If you'd rather always use Lockwise so it would require a user unlock (or any other 3rd party password manager), you can turn off the Fenix logins fill pieces if you don't want to use them by going to Settings -> Logins -> toggling Autofill to off.

**Comment by NJTH317** [comment]
Thanks for the prompt reply.
 
I understand that Firefox is not like Edge, etc., so issues are handled differently. Figuring out how that’s done isn’t always transparent, so I realize I may be going about this the wrong way - I thought I followed the correct procedure for raising this issue I’m having.
 
As far as I know, I’m not using Fenix. I have Firefox for Android, and Lockwise. 
 
When I go to a site where I have saved the credentials, Firefox asks me to unlock with Lockwise AND below that provides suggested logins without me signing in to Lockwise to access those credentials – the screenshot shows that (though I didn’t include my credentials in that screenshot, for obvious reasons).
 
It means Lockwise is not protecting my credentials on these sites, so if my phone were lost or stolen, anyone opening Firefox could access all my credentials.
+++++++++++++++++
(The Rev.) Nigel J. Taber-Hamilton
360-929-3744
 <mailto:rectorhome@whidbey.com> rectorhome@whidbey.com
 <mailto:islandrector@gmail.com> islandrector@gmail.com 
++++++++++++++++
 
Confidentiality Clause

This message is intended for the sole use of the individual and entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are prohibited from forwarding this email or sharing its contents without the permission of the sender. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message. Thank you very much.

**Comment by ekager** [comment]
So the new Firefox for Android is codename Fenix (ie this repo name). 

Please go to Settings -> Logins -> toggling Autofill to off if you don't want to see "Suggested Logins" while using Firefox.

**Comment by kbrosnan** [comment]
Closing as works for me with the pref.

**Comment by NJTH317** [comment]
I replied to direct email from ekager saying that even though I turned off autofill, I'm still getting "Suggested logins" with my username and passwords without signing in to Lockwise.

Closing this thread is NOT solving this problem that I've identified; it's simply ignoring it.

I would appreciate help in fixing this bug, or I'll have to stop using Firefox, and I dont' want to do that.

Thanks.

**Comment by ekager** [comment]
Is it once you start typing the username that the "suggested logins" shows up again? That should be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1663039 (which has already landed, but it takes a while for it to make it to release).

**Comment by NJTH317** [comment]
Apologies that this didn’t send last week – probably my error.
 
What I said then was:
 
“For clarification’s sake, what I have installed is Firefox Daylight 82.1.1 (Build #2015770923). Tho’ Tried that. Didn’t work. Even when toggled off, the auto-suggestions are still there.”
 
+++++++++++++++++
(The Rev.) Nigel J. Taber-Hamilton
360-929-3744
 <mailto:rectorhome@whidbey.com> rectorhome@whidbey.com
 <mailto:islandrector@gmail.com> islandrector@gmail.com 
++++++++++++++++
 
Confidentiality Clause

This message is intended for the sole use of the individual and entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are prohibited from forwarding this email or sharing its contents without the permission of the sender. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message. Thank you very much.

**Comment by ekager** [comment]
Again - Lockwise and Fenix "Suggested Logins" are entirely separate processes. Being logged in to Lockwise or not does not impact the Fenix logins suggestions (which are visible if you are logged into Sync and syncing Logins in Fenix). 

There was a bug as mentioned above that when you start typing the username that matches a login, the "suggested logins" will show up again. That should be fixed by bugzilla.mozilla.org/show_bug.cgi?id=1663039 (which has already landed, but it takes a while for it to make it to release).

I know this is confusing so here are some options: 
- Try to use Nightly which should already have the fix for Suggested Logins showing up when "autofill" is toggled off
- Ignore the Suggested Logins for now and wait for the bug fix to make it to Release

**Comment by NJTH317** [comment]
Okay – got it. Sorry about reopening – I just got the impression you misunderstood what I was saying. I see you closed the reopen – fine with me.
 
I’ve used computers since 1981, and am pretty good about working through problems. 
 
Here, I’m out of my depth. 
 
So forget the Lockwise element. The bottom line is that “suggested logins” displays stuff I don’t want displayed without the application of some sort of Master/primary password or fingerprint.
 
Sounds like this is a known issue.
 
I’ll do what you suggest, and watch.
 
Thanks so much for your help – I love Firefox, and have used it for years, and didn’t want to migrate to another browser.
 
+++++++++++++++++
(The Rev.) Nigel J. Taber-Hamilton
360-929-3744
 <mailto:rectorhome@whidbey.com> rectorhome@whidbey.com
 <mailto:islandrector@gmail.com> islandrector@gmail.com 
++++++++++++++++
 
Confidentiality Clause

This message is intended for the sole use of the individual and entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are prohibited from forwarding this email or sharing its contents without the permission of the sender. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message. Thank you very much.

**Comment by NJTH317** [comment]
Just as a follow-up – I’m not clear on how to pass this on to whomever is working on this security issue:
1.      I installed Nightly.
2.      I synched it with my desktop.
3.      I turned off “Autofill” in “Logins and passwords”
4.      I removed Firefox 82 and rebooted.
5.      It still displays the key icon and “Suggested logons”, with my username and password below that.
 
I’ll check periodically to see if this is still a problem.
 
Thanks so much for your help with this.
 
+++++++++++++++++
(The Rev.) Nigel J. Taber-Hamilton
360-929-3744
 <mailto:rectorhome@whidbey.com> rectorhome@whidbey.com
 <mailto:islandrector@gmail.com> islandrector@gmail.com 
++++++++++++++++
 
Confidentiality Clause

This message is intended for the sole use of the individual and entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are prohibited from forwarding this email or sharing its contents without the permission of the sender. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message. Thank you very much.
 
From: Nigel Taber-Hamilton <rectorhome@whidbey.com> 
Sent: Tuesday, November 3, 2020 2:24 PM
To: 'mozilla-mobile/fenix' <reply@reply.github.com>; 'mozilla-mobile/fenix' <fenix@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [mozilla-mobile/fenix] [Bug] Lockwise does not prevent access to websites credentials (#16288)
 
Okay – got it. Sorry about reopening – I just got the impression you misunderstood what I was saying. I see you closed the reopen – fine with me.
 
I’ve used computers since 1981, and am pretty good about working through problems. 
 
Here, I’m out of my depth. 
 
So forget the Lockwise element. The bottom line is that “suggested logins” displays stuff I don’t want displayed without the application of some sort of Master/primary password or fingerprint.
 
Sounds like this is a known issue.
 
I’ll do what you suggest, and watch.
 
Thanks so much for your help – I love Firefox, and have used it for years, and didn’t want to migrate to another browser.
 
+++++++++++++++++
(The Rev.) Nigel J. Taber-Hamilton
360-929-3744
 <mailto:rectorhome@whidbey.com> rectorhome@whidbey.com
 <mailto:islandrector@gmail.com> islandrector@gmail.com 
++++++++++++++++
 
Confidentiality Clause

This message is intended for the sole use of the individual and entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are prohibited from forwarding this email or sharing its contents without the permission of the sender. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message. Thank you very much.

**Comment by ekager** [comment]
Yeah, I see that and looking at the bugzilla bug again, that was about filling without input. I think this needs UX feedback if we need to add a way to turn off suggested logins separately.

**Comment by NJTH317** [comment]
Thanks so much – that’s a much better summary of the issue than I could come up with. 
 
Thanks for sending this on the the UX folk – how might I know if/when they seek to address the issue?
 
Nigel
+++++++++++++++++
(The Rev.) Nigel J. Taber-Hamilton
360-929-3744
 <mailto:rectorhome@whidbey.com> rectorhome@whidbey.com
 <mailto:islandrector@gmail.com> islandrector@gmail.com 
++++++++++++++++
 
Confidentiality Clause

This message is intended for the sole use of the individual and entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. You are prohibited from forwarding this email or sharing its contents without the permission of the sender. If you are not the intended addressee, nor authorized to receive for the intended addressee, you are hereby notified that you may not use, copy, disclose or distribute to anyone the message or any information contained in the message. If you have received this message in error, please immediately advise the sender by reply email and delete the message. Thank you very much.

**Comment by Djfe** [comment]
The biggest issue here is that you can't select "not to sync passwords" from your Firefox Account on first login!
It will always download all passwords to Firefox even if you prefer Lockwise.
If you uncheck it, then it only stops syncing but there is no way to remove them from your device after the first sync.

If you remove them manually, entry-by-entry, then that's not only very tedious but also risky. Should you ever sync logins again, even by mistake, then all those deletions would be synced as well.

@NJTH317 is right, there are some bugs here. tl;dr
1. You can't disable Firefox's login form on top of the keyboard. (not to be confused with "autofill" , which will in passwords on page load automatically without asking you first, this you can disable)
2. Syncing your Firefox account doesn't let you choose which data to sync on first sync.
3. You cannot empty your password storage at once, should you ever decide to switch to an actual password manager.

**Comment by Djfe** [comment]
This is still happening in Nightly. We just want a way to hide "suggested logins" without deleting all logins.

**Comment by Rodze** [comment]
Stale not should close the entire repository as stale.

What useless metric.

**Comment by Djfe** [comment]
Was that supposed to be funny? Go vent somewhere else like irc, this is a bug report.
