### ISSUE TITLE
[Bug] After 0105 Update, Accessing Non-English Websites Causes Crashes

### ISSUE THREAD

**Issue by sharbet** [mozilla-mobile/fenix#17306]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Connect to Korean websites
1. m.daum.net
2. namu.wiki
3. m.dcinside.com
4. m.inven.co.kr/maple

### Expected behavior
Fenix should work fine without problem

### Actual behavior
Fenix crashes to home.
(I can access NTP fine. Accessing those sites causes crashes. Prior to this update, I was able to access those websites fine)

[https://mega.nz/file/nQEBlIwD#rKfmJqnxiCNvzeUDnWxDGgmaXorWaAaBBF6UkvTJxRI](url)

### Device information

* Android device: Galaxy S20+ (Android 11, OneUI 3.0)
* Fenix version: 210105 (Latest update as of writing this)

**Comment by makotokato** [comment]
@sharbet
Is this Nightly only?  If so, it will be https://bugzilla.mozilla.org/show_bug.cgi?id=1684846. (Upstream's GV has been fixed, but it isn't rolled out to Fenix yet.)

**Comment by sharbet** [comment]
@makotokato yeah, it seems it's Nightly only. Glad the problem will be fixed in upcoming updates.

**Comment by kbrosnan** [comment]
We are spinning a new nightly to resolve this crash. There is not any code to check into this repository, closing.

**Comment by yan12125** [comment]
Hi thanks for the update. Does the following version include the fix?

```
Nightly 210105 17:01 (Build #2015785611)
AC: 71.0.20210105122039, b1b5b2056
GV: 86.0a1-20210104090857
AS: 67.2.0
```

It still crashes with at least the following URLs:
https://www.rti.org.tw/
https://www.ithome.com.tw/

Corresponding crash reports do not unveil much insight. Both say "no crashing thread identified".
https://crash-stats.mozilla.org/report/index/546a1d79-997c-4ac7-9bad-0431c0210106
https://crash-stats.mozilla.org/report/index/9d65b23f-15b3-44a1-85d0-2ee6e0210106

**Comment by makotokato** [comment]
> Hi thanks for the update. Does the following version include the fix?

No.  If GV is 86.0a1-20210106093742 or later, this will be fixed.

**Comment by yan12125** [comment]
Thanks! I can confirm Fenix no longer crashes on aforementioned sites.
