### ISSUE TITLE
FNX3-15862 ⁃ [Bug] pressing back with open address bar should not close Fenix

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1854]
### Steps to reproduce
1. open the adressbar
1. press the back key of your device

### Expected behavior
You returns to the home screen of Fenix.

### Actual behavior
Fenix is closed.

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 080dadcb7e1cc0aa53c020595505f6f493e4a143

**Comment by cadeyrn** [comment]
The same applies for the QR code scanner: If you accidentally starts the QR code scanner and press back to close it Fenix closes instead of returning to either the open address bar or the Fenix home screen.

**Comment by vesta0** [comment]
I believe this is fixed.

**Comment by cadeyrn** [comment]
> I believe this is fixed.

No, it's not fixed with latest version from master.

**Comment by sv-ohorvath** [comment]
I cannot reproduce the issue. 
Devices: Pixel (Android 9) &HTC Desire 820 (Android 6.0.1). 
Build: 4/24. 
@cadeyrn Please check again and close if it's fixed for you too.

![20190425_163202](https://user-images.githubusercontent.com/4037709/56739610-cb3c3300-6777-11e9-8b5a-423c20327808.gif)

**Comment by cadeyrn** [comment]
Yes, it's still an issue. I can make a screencast later today.

**Comment by cadeyrn** [comment]
![20190425_193136](https://user-images.githubusercontent.com/1100614/56756067-3b0ae780-6791-11e9-876d-da3fc11d4a9c.gif)

**Comment by kbrosnan** [comment]
You are each using a different entry point. Unclear where @cadeyrn is tapping but maybe it is the "Search or enter address". @sv-ohorvath is tapping on the plus button.

**Comment by kbrosnan** [comment]
I tried reproducing cadeyrn's results on a HTC U11+ HTC_2Q4D100 and was not able to reproduce.

**Comment by cadeyrn** [comment]
> You are each using a different entry point. Unclear where @cadeyrn is tapping but maybe it is the "Search or enter address". @sv-ohorvath is tapping on the plus button.

Yes, I tapped "Search or enter address" but using the plus button doesn't make a difference.

Is there anything I can do to help debugging the issue?

**Comment by kbrosnan** [comment]
Would you try a taskcluster build? https://tools.taskcluster.net/index/project.mobile.fenix.signed-nightly.nightly.2019.4.26/latest

**Comment by cadeyrn** [comment]
Same issue with the taskcluster build.

Please note that sometimes it always happens but sometimes it works as expected so you have to test multiple times.

**Comment by bifleming** [comment]
@kbrosnan is this still blocked?

**Comment by cadeyrn** [comment]
I don't know what fixed it but I can no longer reproduce.

**Comment by cadeyrn** [comment]
For the record: This issue was fixed by the androidx dependencies update in #2350.
