### ISSUE TITLE
[Bug] Scrolling down/up or typing causes odd structures and shapes to be formed on pages (after updating to 89.1.1)

### ISSUE THREAD

**Issue by Siva981** [mozilla-mobile/fenix#19783]
## Steps to reproduce
Scrolling down or up inside web pages, or typing inside a web page displays weird structures or shapes that are being randomly formed throughout the page. They disappear again if I scroll up or down. This behavior started after I updated my Firefox For Android from version 88.1.4 to version 89.1.1.

### Expected behavior
Scrolling or typing should not cause weird shapes to be formed throughout web pages.

### Actual behavior
1) Random, weird structures keep forming and disappearing throughout the web pages when scrolling down or up.
2) Weird structures seem to appear around boxes while I am typing inside them. They are forming even around this github issue creation box, the one I am typing this to create an issue. They keep forming and disappearing randomly as I type.

### Device information

* Device vendor / model and Android version: 
Swipe Elite Plus
Android 5.0.1
Qualcomm Snapdragon 615

* Firefox for Android version:
89.1.1 (Build #2015812947)
AC: 75.0.22, 5204f4025
GV: 89.0-20210527174632
AS: 74.0.1

### Screenshots
 
![IMG_20210603_043157](https://user-images.githubusercontent.com/44178186/120562816-ce10b400-c424-11eb-9496-976ebd26cab3.jpg)
.
![IMG_20210603_043003](https://user-images.githubusercontent.com/44178186/120562819-d10ba480-c424-11eb-841a-e74702919e54.jpg)
.
![IMG_20210603_042902](https://user-images.githubusercontent.com/44178186/120562823-d36dfe80-c424-11eb-9655-f0dcca10153b.jpg)
.
![IMG_20210603_042818](https://user-images.githubusercontent.com/44178186/120562829-d537c200-c424-11eb-9338-509e8e0b7b78.jpg)
.
![IMG_20210603_042659](https://user-images.githubusercontent.com/44178186/120562831-d7018580-c424-11eb-89be-0d1d9bf91579.jpg)
.
![IMG_20210603_042612](https://user-images.githubusercontent.com/44178186/120562835-d8cb4900-c424-11eb-8532-b8eedaae774b.jpg)
.
![IMG_20210603_042505](https://user-images.githubusercontent.com/44178186/120562839-da950c80-c424-11eb-812f-1454f48fb905.jpg)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1714227

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by jamienicol** [comment]
Hi @Siva981, thank you for the bug report.

Could you please navigate to about:support, click on the "Copy text to clipboard" button, then attach the text to this bug (or on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1714227).

Since you say this used to work in version 88, would you be able to run [mozregression](https://mozilla.github.io/mozregression/install.html) to find out what caused it? That would be incredibly helpful. You can install the GUI from the website there, or if you have a Linux desktop I find it's easiest to install via the command line using `pip install --user mozregression`.

You can then plug your phone in to your computer, then on the computer run the mozregression GUI app and click the scissor icon to run a new bisection. You need to select `gve` in the dropdown menu where it says "Application". Then click next twice, then when it says "Build selection", change the dropdown menus from "date" to "release", and enter 88 for "good" and 89 for "bad". Then click "Finish".

Or alternatively, if using the command line, run `mozregression --app gve --good 88 --bad 89`.

This will download and run a series of versions of firefox on your phone. For each one, select "good" or "bad". Eventually this will tell you what caused the bug.

If you need any help with that please let me know. Thanks!

**Comment by Siva981** [comment]
## Content from about:support (Copy text to clipboard)



      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="app-basics-title">Application Basics</h2>

      
Name | Firefox
-- | --
89.0
20210527174632
&nbsp;
Mozilla/5.0 (Android 5.0.2; Mobile; rv:89.0) Gecko/89.0 Firefox/89.0
Linux 21 #1 SMP PREEMPT Wed May 11 11:02:08 CST 2016
0/0
0/0               Disabled by default
1
Found
Found
Found
false



      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" id="crashes-title" data-l10n-id="report-crash-for-days" data-l10n-args="{&quot;days&quot;:3}">Crash Reports for the Last 3 Days</h2>

      
Report ID | Submitted
-- | --



      
      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="features-title">Nightly Features</h2>

      
Name | Version | ID
-- | -- | --




      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="processes-title" id="remote-processes">Remote Processes</h2>

      
Type | Count
-- | --
Web Content | 1 / 1



      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="support-addons-title">Add-ons</h2>

      
Name | Type | Version | Enabled | ID
-- | -- | -- | -- | --
HTTPS Everywhere | extension | 2021.4.15 | true | https-everywhere@eff.org
Mozilla Android Components - Ads | extension | 75.0.22.0528020506 | true | ads@mozac.org
Mozilla Android Components - Browser Icons | extension | 75.0.22.0527234221 | true | icons@mozac.org
Mozilla Android Components - Cookies | extension | 75.0.22.0528020506 | true | cookies@mozac.org
Mozilla Android Components - Firefox Accounts WebChannel | extension | 75.0.22.0527234112 | true | fxa@mozac.org
Mozilla Android Components - ReaderView | extension | 75.0.22.0527234242 | true | readerview@mozac.org
Mozilla Android Components - Web Compatibility Interventions | extension | 22.0.0 | true | webcompat@mozilla.org
Privacy Badger | extension | 2021.6.8 | true | jid1-MnnxcxisBPnSXQ@jetpack
uBlock Origin | extension | 1.35.2 | true | uBlock0@raymondhill.net



      

      

      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="graphics-title">Graphics</h2>

      
Features
--
WebRender
touch input enabled; autoscroll enabled; smooth pinch-zoom enabled
EGL_VENDOR: Qualcomm, Inc EGL_VERSION: 1.4 EGL_EXTENSIONS: EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_lock_surface3 EGL_KHR_fence_sync EGL_KHR_cl_eventEGL_KHR_cl_event2EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_ANDROID_framebuffer_target EGL_KHR_create_context EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_ANDROID_image_crop EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_KHR_gl_colorspace EGL_IMG_image_plane_attribs  IsWebglOutOfProcessEnabled: 0
Qualcomm -- Adreno (TM) 405
OpenGL ES 3.0 V@100.0 AU@  (GIT@I68fa98814b)
GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query
ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_sRGB EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_lose_context
EGL_VENDOR: Qualcomm, Inc EGL_VERSION: 1.4 EGL_EXTENSIONS: EGL_QUALCOMM_shared_image EGL_KHR_image EGL_KHR_image_base EGL_QCOM_create_image EGL_KHR_lock_surface EGL_KHR_lock_surface2 EGL_KHR_lock_surface3 EGL_KHR_fence_sync EGL_KHR_cl_eventEGL_KHR_cl_event2EGL_IMG_context_priority EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_renderbuffer_image EGL_EXT_create_context_robustness EGL_ANDROID_blob_cache EGL_ANDROID_framebuffer_target EGL_KHR_create_context EGL_KHR_wait_sync EGL_KHR_gl_colorspace EGL_ANDROID_image_crop EGL_ANDROID_recordable EGL_ANDROID_native_fence_sync EGL_ANDROID_image_native_buffer EGL_KHR_gl_colorspace EGL_IMG_image_plane_attribs  IsWebglOutOfProcessEnabled: 0
Qualcomm -- Adreno (TM) 405
OpenGL ES 3.0 V@100.0 AU@  (GIT@I68fa98814b)
GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_sync GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_filter_anisotropic GL_EXT_multisampled_render_to_texture GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query
EXT_color_buffer_float EXT_texture_filter_anisotropic MOZ_debug WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context
true
true
60

Yes
Model: Elite Plus, Product: Elite_Plus, Manufacturer: SWIPE, Hardware: qcom, OpenGL: Qualcomm -- Adreno (TM) 405 -- OpenGL ES 3.0 V@100.0 AU@  (GIT@I68fa98814b)
Qualcomm
Adreno (TM) 405
OpenGL ES 3.0 V@100.0 AU@  (GIT@I68fa98814b)
0


skia
skia
none
Empty profile data
1080x1920
1
512
512

available by defaultforce_enabled by user: Force-enabled by pref | available by default | force_enabled by user: Force-enabled by pref
available by default
force_enabled by user: Force-enabled by pref
available by defaultforce_enabled by user: Force-enabled by pref | available by default | force_enabled by user: Force-enabled by pref
available by default
force_enabled by user: Force-enabled by pref
available by default | available by default
available by default
available by default | available by default
available by default
disabled by default: Disabled by default | disabled by default: Disabled by default
disabled by default: Disabled by default
available by default | available by default
available by default
available by default | available by default
available by default
available by default | available by default
available by default
available by defaultunavailable by env: OS not supported | available by default | unavailable by env: OS not supported
available by default
unavailable by env: OS not supported
available by defaultdisabled by user: User disabled via prefunavailable by env: Requires Windows 10 or laterunavailable by runtime: Requires ANGLE | available by default | disabled by user: User disabled via pref | unavailable by env: Requires Windows 10 or later | unavailable by runtime: Requires ANGLE
available by default
disabled by user: User disabled via pref
unavailable by env: Requires Windows 10 or later
unavailable by runtime: Requires ANGLE
available by defaultdenied by env: Not on allowlist | available by default | denied by env: Not on allowlist
available by default
denied by env: Not on allowlist
disabled by default: Disabled by defaultbroken by runtime: OMTP is not supported with &lt; 2 GB RAM | disabled by default: Disabled by default | broken by runtime: OMTP is not supported with &lt; 2 GB RAM
disabled by default: Disabled by default
broken by runtime: OMTP is not supported with &lt; 2 GB RAM
disabled by default: Disabled by defaultblocked by runtime: WebGPU can only be enabled in nightly | disabled by default: Disabled by default | blocked by runtime: WebGPU can only be enabled in nightly
disabled by default: Disabled by default
blocked by runtime: WebGPU can only be enabled in nightly



Failed to load a program object with a program binary: cs_scale renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: brush_opacity renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: composite renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: composite renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: ps_text_run renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: ps_text_run renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: brush_image renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary
Failed to load a program object with a program binary: brush_image renderer Adreno (TM) 405 Invalid binary image passed to glProgramBinaryOES.
shader-cache: Failed program_binary



      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="media-title">Media</h2>
      
Audio Backend | opensl
-- | --
2
48000
...


Default audio output device | &nbsp; | &nbsp; | Enabled | All | default: S16LE, support: S16LE S16BE F32LE F32BE | 2 | default: 44100, support: 44100 - 44100 | 128 - 441


Default audio input device | &nbsp; | &nbsp; | Enabled | All | default: S16LE, support: S16LE S16BE F32LE F32BE | 1 | default: 44100, support: 44100 - 44100 | 128 - 441

Enumerate database



      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="environment-variables-title">Environment Variables</h2>

      


      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="modified-key-prefs-title">Important Modified Preferences</h2>

      
extensions.lastAppVersion | 89.0
-- | --
idle.lastDailyNotification | 1623652202
media.gmp.storage.version.observed | 1
network.dns.disablePrefetch | true
network.http.speculative-parallel-limit | 0
network.predictor.enabled | false
network.prefetch-next | false
network.trr.blocklist_cleanup_done | true
privacy.purge_trackers.date_in_cookie_database | 0
privacy.purge_trackers.last_purge | 1623652203081
security.remote_settings.crlite_filters.checked | 1623703178
security.remote_settings.intermediates.checked | 1623703178
storage.vacuum.last.index | 0



      

      

      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="locked-key-prefs-title">Important Locked Preferences</h2>

      
fission.autostart.session | false
-- | --





      
      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="a11y-title">Accessibility</h2>

      
Activated | true
-- | --
0



      
      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="library-version-title">Library Versions</h2>

      
&nbsp; | Expected minimum version | Version in use
-- | -- | --
NSPR | 4.30 | 4.30
NSS | 3.64 | 3.64
NSSSMIME | 3.64 | 3.64
NSSSSL | 3.64 | 3.64
NSSUTIL | 3.64 | 3.64



      


      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="startup-cache-title">Startup Cache</h2>

      
Disk Cache Path | /data/data/org.mozilla.firefox/files/mozilla/r4lhlwbl.default/startupCache/startupCache.8.little
-- | --
false
true
false



      <h2 xmlns="http://www.w3.org/1999/xhtml" class="major-section" data-l10n-id="intl-title">Internationalization &amp; Localization</h2>

      
Application Settings
--
["en-US"]
["an","ar","ast","az","be","bg","bn","br","bs","ca","cak","cs","cy","da","de","dsb","el","en-CA","en-GB","en-US","eo","es-AR","es-CL","es-ES","es-MX","et","eu","fa","ff","fi","fr","fy-NL","ga-IE","gd","gl","gn","gu-IN","he","hi-IN","hr","hsb","hu","hy-AM","id","is","it","ja","ka","kab","kk","kn","ko","lij","lo","lt","lv","ml","mr","ms","my","nb-NO","ne-NP","nl","nn-NO","oc","pa-IN","pl","pt-BR","pt-PT","rm","ro","ru","sk","sl","son","sq","sr","sv-SE","ta","te","th","tr","trs","uk","ur","uz","vi","wo","xh","zam","zh-CN","zh-TW"]
["en-US","en-CA","en-GB"]
["en-US"]
"en-US"

["en-US"]
["en-US"]

**Comment by Siva981** [comment]
Hi @jamienicol,

Thank you for taking a look at this issue.

Unfortunately, I don't have access to a computer right now. And due to the Covid-19 lockdowns still in effect at my place, I might not have access to one for another month or so. Because the closest accessible PC (one where I could install or run my own software anyway) is nearly 400 kilometers away. I apologize for not being able to help with anything that needs a computer.

I have posted the about:support report though, as you had requested. 

Please let me know if there is anything else I could do, with only my mobile, to help initiate the resolution of this issue.

Thank You In Advance!

P.S:
My current location is Salem (Tamil Nadu, India)

**Comment by jamienicol** [comment]
Hi Siva, thanks for the about:support!

That's no problem about your lack of access to a computer, I will try to get my hands on a similar device to debug further.

**Comment by jamienicol** [comment]
Hi @Siva981, sorry for the long delay getting back to you. This proved to be quite a tricky bug to figure out, but I *think* I have found the issue. (In fact, I think there were 2 separate issues)

I would be grateful if you could test a few APKs for me, and attach screenshots if possible. The first two try to fix each of the 2 issues separately, so I'd expect it still to look buggy. But with a screenshot I should be able to verify that they each fix a different thing. And the last APK should hopefully fix it completely.

1. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/aprboYJKQROxY-ifPt3LSA/runs/0/artifacts/public/build/geckoview_example.apk
2. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/L67YRs9lRVy2qfrX_HdOOw/runs/0/artifacts/public/build/geckoview_example.apk
3. https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/EwxfvenvRZSv-rmgLowdvg/runs/0/artifacts/public/build/geckoview_example.apk

**Comment by Siva981** [comment]
Hi @jamienicol,

Thank you for your time and effort to look into this. 

I will install and test these APKs (hopefully by this weekend; if possible earlier than that) and get back to you as soon as I do. 

Thank You!

**Comment by Nickoriginal** [comment]
Hello! _Not reproducible_ in Firefox 90.1.1 on:
**Samsung Galaxy A20s** (Android 10)
**Samsung Galaxy J2 Prime** (Android 6.0.1)
At this time I don't find users who can reproduce it on Android 6 or higher.

**Comment by Nickoriginal** [comment]
Hello! _Not reproducible_ in Firefox 90.1.1 on:
**Samsung Galaxy A20s** (Android 10)
**Samsung Galaxy J2 Prime** (Android 6.0.1)
At this time I don't find users who can reproduce it on Android 6 or higher. Unfortunately, I haven't devices with Android 5 installed.

**Comment by jamienicol** [comment]
Hi @Emojigit, could you please try out the builds linked a few comments above and see if they help at all?

I expect they might fix the issues in your second screenshot it #20323, but not the first screenshot.

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/19783

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/19782

**Comment by Nickoriginal** [comment]
https://github.com/mozilla-mobile/fenix/issues/20323

**Comment by Siva981** [comment]
Hi @jamienicol,

I finally got some down time to test the 3 APKs out. Apologies for the long delay.

## Test Results 

I have managed to capture similar screenshots of the same pages (7 each), for all the 3 APKs. For clarity and ease, I am posting them as 3 separate comments.

Please take a look and proceed further.

Thank You In Advance!

**Comment by Siva981** [comment]
# Test Results 
The same 4 results are posted for all 3 APKs.

### Note 
Apart from the weird structure formation defect that we are debugging as part of this github issue, the update to Firefox For Android from version 88.1.4 to version 89.1.1, also caused a couple more deal breaking issues in my Android 5.0.2 phone, for which I had created separate github issues at the time. I would like to let you know their test results as well.

## Gecko View APK 1

1) The weird artefacts, structures, and shapes, which randomly form around images, links, etc, are mostly gone in this APK.

2) That said, the structures are still momentarily appearing and disappearing whenever I click on small editable boxes. A couple of good examples, would be the username and password boxes in the Sign In pages for the Gmail and GitHub websites. 

3) As I had reported in the issue #19782, all the editable boxes, clickable buttons and option buttons are still not displayed correctly. Clickable buttons and editable boxes have double borders. Also, they seem to have these small triangle shaped structures at their corners. As for option buttons, they look like large, irregularly shaped commas. Please refer that issue for related screenshots.

4) Also, as I had reported in the issue #19787, the HTML View of Gmail operates entirely in slow motion. Double Tap to zoom does not zoom up to the expected zoom level (please refer that issue for related screenshots). Also, double tap to zoom happens in a very slow motion. Same is the case with pinch to zoom. It is very slow.

## Screenshots 

### 1
![IMG_20210802_065322](https://user-images.githubusercontent.com/44178186/127947195-5ed12fbe-876f-4056-9ced-7e919c08114e.jpg)
### 2
![IMG_20210802_064839](https://user-images.githubusercontent.com/44178186/127947279-6ed1e2a7-bc28-46cc-8f63-bd05b8d2f908.jpg)
### 3
![IMG_20210802_065054](https://user-images.githubusercontent.com/44178186/127947350-b3b2c88a-5d4a-48d2-a120-f53ac1bd38c4.jpg)
### 4
![IMG_20210802_064435](https://user-images.githubusercontent.com/44178186/127947483-3cad9f2b-15e3-4639-986f-65ccdb10f2df.jpg) 
### 5
![IMG_20210802_063929](https://user-images.githubusercontent.com/44178186/127947599-85f715e2-6e32-4bb6-ab3d-992744865254.jpg)
### 6
![IMG_20210802_064209](https://user-images.githubusercontent.com/44178186/127947915-0167a73d-ca26-48a4-8ab1-19545fb096a3.jpg)
### 7
![IMG_20210802_064638](https://user-images.githubusercontent.com/44178186/127947705-29535a11-0eaa-4627-b410-af8984a00c7b.jpg)

**Comment by Siva981** [comment]
## Gecko View APK 2

1) The weird structures are **back** in this APK. The issue still persists.

2) Same result as in APK 1. The issue still persists.

3) Same result as in APK 1. The issue still persists.

4) Same result as in APK 1. The issue still persists.

## Screenshots 
### 1
![IMG_20210802_083711](https://user-images.githubusercontent.com/44178186/127949335-daa56807-4fbc-4297-8029-827988cc31d0.jpg)
### 2
![IMG_20210802_083546](https://user-images.githubusercontent.com/44178186/127949408-2a6c1b7e-8f01-4889-8aa0-bcda15a16004.jpg)
### 3
![IMG_20210802_083810](https://user-images.githubusercontent.com/44178186/127949441-cd410170-18e8-4706-b683-81a6398ce6c1.jpg)
### 4
![IMG_20210802_083035](https://user-images.githubusercontent.com/44178186/127949481-9bf9e878-e11b-45a2-8b60-5a663ee93b3d.jpg)
### 5
![IMG_20210802_083150](https://user-images.githubusercontent.com/44178186/127949567-9ee6b1b0-63fd-40e5-b5e0-aa2b278ec2e9.jpg)
### 6
![IMG_20210802_083336](https://user-images.githubusercontent.com/44178186/127949621-e60c2b4b-d0c8-4620-8f9a-511dc65b58c4.jpg)
### 7
![IMG_20210802_083928](https://user-images.githubusercontent.com/44178186/127949683-6e534fb7-e1b7-4294-9df6-a3a33a978262.jpg)

**Comment by Siva981** [comment]
## Gecko View APK 3
All the 4 test results are exactly the same as in **APK 1**. No further improvement.

## Screenshots 
### 1
![Screenshot_2021-08-02-09-32-05](https://user-images.githubusercontent.com/44178186/127950527-32772b8b-5cda-4134-bdda-abc599ba81fd.png)
### 2
![Screenshot_2021-08-02-09-20-18](https://user-images.githubusercontent.com/44178186/127950658-5b07ff2c-013a-44e9-9577-578c8d4096c8.png)
### 3
![Screenshot_2021-08-02-09-21-18](https://user-images.githubusercontent.com/44178186/127950728-47261a16-51ea-40f1-81f3-d5e3a94f3598.png)
### 4
![Screenshot_2021-08-02-09-08-26](https://user-images.githubusercontent.com/44178186/127950764-24825e34-b163-4ff0-ad7d-e5f4de1de4ce.png)
### 5
![Screenshot_2021-08-02-09-06-13](https://user-images.githubusercontent.com/44178186/127950831-7f735a07-5b33-4df3-971a-d16740199df8.png)
### 6
![Screenshot_2021-08-02-09-11-44](https://user-images.githubusercontent.com/44178186/127950960-bbac65bf-aaf4-41fe-a13c-10e230ff5b47.png)
### 7
![Screenshot_2021-08-02-09-09-28](https://user-images.githubusercontent.com/44178186/127950998-b3b6bf94-71e7-4ee6-8981-d395ac7b978d.png)

**Comment by jamienicol** [comment]
Thanks for the detailed testing @Siva981!

The problem with the button corners and the triangular shapes within the buttons should have been fixed in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1721795). If you could test the latest Firefox Nightly to confirm that would be great.

For the "weird artefacts, structures, and shapes, which randomly form around images, links", it sounds like APK 1 and 3 mostly fixed them. I'm currently working on getting this fix merged. It would be very helpful if you could attach a screenshot of this still occuring with APK 1 or 3, as I can only see them in your APK 2 screenshots above.

**Comment by Siva981** [comment]
Hi @jamienicol,

I could not grab a screenshot from APK1 or APK3, for the username/pwd boxes of login pages, was because, like I had mentioned, the structures stay only for a couple of seconds after the page completes loading or after we click into those boxes. 

That said, we could still see those large triangle shaped formations inside the editable boxes, of the screenshot number 7, from my test results for both APK1 and APK3.

I installed APK1 again today. After a lot of attempts, I finally managed to capture a screenshot of the structure appearing on one of the sign up pages. I have also captured new screenshots, wherein I have highlighted editable boxes have structures inside of them. 

Please take a look.

## Screenshots (APK 1)
### 1
![IMG_20210807_071037](https://user-images.githubusercontent.com/44178186/128584616-206a9d3f-7bae-4be5-9d14-5dffd10e7967.jpg)
###2
![IMG_20210807_071330](https://user-images.githubusercontent.com/44178186/128584624-2c3d98fc-0299-4b8e-b7da-213fc1028e9b.jpg)
###3
![IMG_20210807_071428](https://user-images.githubusercontent.com/44178186/128584655-407df72d-54cb-4c25-bae3-c5268800cfeb.jpg)

**Comment by Siva981** [comment]
Hi @jamienicol,

Per your other request in your previous comment, I also tested the latest Nightly (92.0a1). 

There was some encouraging test results here. 

## What's Working 
1) Clickable Buttons, Editable Boxes, Option Buttons, etc, look good now. There are no double borders or triangle shaped corners around them.

2) Surprisingly, the structure formation is gone now too. The random structures, shapes, etc, are no longer appearing around or inside of images, links or editable boxes.

## Issues 
That said, the issues I had mentioned in issue #19787 are still there. If anything, I felt they were even more a hindrance to the browsing experience than they are in the current Firefox For Android. Everything is very slow.

1) Double Tap to Zoom still does not scale the Gmail HTML version's Inbox page up to the desired level (please refer aforementioned issue for details).

2) Zoom In and Zoom out still happens in slow motion. Now, it is even slower.

3) Swiping/Scrolling the pages up or down is an arduous task here. It is extremely slow. Even though the current Firefox For Android is similarly buggy, Nightly seems worse to me. Everything was operating in a very slow motion.

It would be great if we could resolve this issue too. Please take a look.

## Screenshots (Nightly) 
### 1
![Screenshot_2021-08-07-06-17-35](https://user-images.githubusercontent.com/44178186/128585375-89b89cb8-6199-4e8e-9e1a-72bb7538b6f0.png)
### 2
![Screenshot_2021-08-07-06-05-19](https://user-images.githubusercontent.com/44178186/128585382-4ced1646-91d5-47d1-ad2f-5acab7586805.png)
### 3
![Screenshot_2021-08-07-06-06-23](https://user-images.githubusercontent.com/44178186/128585404-0f47620d-e4c0-45fb-8fad-10d4d1341f2a.png)
### 4
![Screenshot_2021-08-07-05-54-43](https://user-images.githubusercontent.com/44178186/128585433-6061095f-422d-4063-8126-f249a1b11511.png)
### 5
![Screenshot_2021-08-07-05-49-19](https://user-images.githubusercontent.com/44178186/128585446-4fb2c04c-88d4-45f1-9936-51248510d7e8.png)
### 6
![Screenshot_2021-08-07-05-49-40](https://user-images.githubusercontent.com/44178186/128585461-403df7d2-18ae-4862-9af1-e0ff47223313.png)
### 7 
![Screenshot_2021-08-07-05-57-42](https://user-images.githubusercontent.com/44178186/128585473-062ba225-10a5-42d3-b047-d0c10ac69759.png)

**Comment by jamienicol** [comment]
Hi @Siva981, thanks for your latest screenshots of APK 1. I know the glitches all look similar but those are actually due to the same bug as the other APK 1 shapes, rather than the ones that remained in APK 2. The difference is that these shapes are usually triangular and entirely within the size of the element being drawn. They were fixed in nightly in bug 1721795.

The glitches that remained APK 2 (which are more strange shapes and extend outside of the element being drawn) have been temporarily fixed in nightly in bug 1720169. It's good to hear you confirm that nightly has fixed the issue. Unfortunately this change will temporarily have to be reverted as it has caused some other issues, but at least we now know how to fix them and hopefully it should be fixed for good on nightly soon.

For the slowness, are you still without access to a desktop computer? If you had access it would be very helpful to grab a performance profile.

One thing to try in nightly, is going to `about:config` and setting `gfx.webrender.debug.batched-texture-uploads` to true, restart, and see if that helps. If not, then also try setting `gfx.webrender.debug.draw-calls-for-texture-copy` to true and restart.

**Comment by Siva981** [comment]
Hi @jamienicol,

I tested Nightly again, initially after toggling the first value you had mentioned to True, restarting Nightly (Using the 'Quit' option from Nightly's Menu, and then doing a 'Force Stop' of the app in Android Settings) before testing it, and then after toggling both the values you had mentioned to True and Restarting Nightly again.

Unfortunately, in both the scenarios, there was little to no improvement from the earlier test results when I tested Nightly.

**Comment by Emojigit** [comment]
Sorry the phone having the problem is broken xd

Jamie Nicol ***@***.***> 於 2021年7月12日週一 下午10:32 寫道：

**Comment by Siva981** [comment]
Hi @jamienicol,

My Firefox For Android was updated today, from version 90.1.3 to version 91.1.0.

1) Buttons and boxes look good now (Issue #19782)

2) The issues pertaining to this github issue (#19783) still persists. Structures are still appearing outside of the elements being drawn (citing your earlier explanation).

3) The issues pertaining to issue #19787 are still there too. The zoom in/out issues and the scroll left/right/down/up issues are still there. They are slowing down normal operations.

That said, the scrolling/zooming slowness is not as bad as in Nightly 92.0a1.

The current slowness of these operations is more or less equal to the previous stable version I had (90.1.3).

So I am assuming, that whatever caused the extreme slowness when I tested Nightly 92.0a1, was probably introduced with the solution (which you informed was backed out from going live) for the strange structures issue.

### Copy Pasted From About Firefox
91.1.0 (Build #2015826187)
AC: 91.0.12, 1d401758fb
GV: 91.0-20210804193234
AS: 79.0.0

2021-08-05T01:38:45.324

**Comment by jamienicol** [comment]
Hi @Siva981, yes it appears you are correct, the patch that fixed the glitches also caused the performance regression (and caused other glitches on devices...)

I'm working on another solution now. Thank you for your patience - as you can see this is difficult, working around a driver bug on some devices can make us run in to different driver bugs instead.

**Comment by Siva981** [comment]
Hi @jamienicol,

Any luck on the new solution? :)

Thank You In Advance!

**Comment by Siva981** [comment]
This issue's related bugzilla defect seems to have been closed. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1714227

Is this issue (#19783) not worked on anymore? 

I am still facing the odd shapes/structures issue. I am on Firefox For Android version 94.1.2. 

I have been having this issue for a long time now, ever since version 89.1.1 :(
