### ISSUE TITLE
[Bug]: No open tabs in tab tray

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#21364]
### Steps to reproduce

Open Fenix with no tabs open
Open one tab
Select the tabs icon in the awesomebar

### Expected behaviour

Tab tray shows one open tab.

### Actual behaviour

Tab tray shows no open tabs

Tab tray will show tabs if more tabs are opened - so to close tabs you have to open another tab to then close two tabs.

### Device name

Motorola Moto E5

### Android version

Android 8

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1

**Comment by jonalmeida** [comment]
@SeburoSUMO does the tab counter indicate that there is at least one tab?

This sounds like https://github.com/mozilla-mobile/fenix/pull/21361 which we just fixed and should be out in a few hours.

**Comment by SeburoSUMO** [comment]
It was yes...but now I am struggling to replicate it.

**Comment by jonalmeida** [comment]
You can replicate this by closing all tabs and clicking on only a top site.

**Comment by SeburoSUMO** [comment]
I tried that, but still cannot replicate it.

I can assure you that it did happen - and several times - before I reported it.

**Comment by jonalmeida** [comment]
Sorry, close all tabs, then search of results and open tabs only from the search page.

**Comment by SeburoSUMO** [comment]
Yes - that does it!

My bad, I should have made the str a bit more verbose.

**Comment by sheikh-azharuddin** [comment]
This bug was introduced after adding grouping feature in tabs which is another buggy feature

**Comment by jonalmeida** [comment]
The fix is released. Closing.
