### ISSUE TITLE
[Bug]: The latest synced tab is displayed in the Jump Back In section when no tabs are open on other devices

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/fenix#26406]
### Steps to reproduce

1. On a mobile device login in with a Firefox account and open a few tabs;
2. On a second device login with the same account and observe the homepage;
3. On the first device delete all open tabs and wait for or perform a manual sync;
4. Observe the home screen of the second device.

### Expected behaviour

At step 2 the last accessed tab from the first device should be displayed on the home screen but at step 4 it should disappear since there are no other open tabs on other synced devices.

### Actual behaviour

At step 4 the last accessed tab from the first device is displayed in the Jump back in section on the second device even though there are no open tabs on other devices.

### Devices used
- Google Pixel 6 (Android 13)
- Samsung Galaxy S22 Ultra (Android 12)

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1 2022-08-10

### Additional information

https://user-images.githubusercontent.com/50983519/183883320-d0a62c2b-b4a9-45a2-b960-787a31010da1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21251)

**Comment by rocketsroger** [comment]
@mhammond is this issue fixed with [bug 1783991](https://bugzilla.mozilla.org/show_bug.cgi?id=1783991) as well?  Thanks

**Comment by mhammond** [comment]
No, that bug only affected the list of tabs for desktop devices, so if this STR involves only Fenix devices it is not related.

**Comment by mhammond** [comment]
(The first step here would be to ensure that Fenix actually tells the application-services component about the empty list of tabs in that case)

**Comment by rocketsroger** [comment]
@mhammond This is actually unreproducible with Fenix tabs.  I can only reproduce it by closing the Firefox desktop browser.  I can also reproduce this with just two Firefox Nightly on desktop as well.

**Comment by mhammond** [comment]
The STR involve 2 Fenix devices, so I assume that's what we were still talking about. It still doesn't sound like bug [1783991](https://bugzilla.mozilla.org/show_bug.cgi?id=1783991) but I guess it could be related.

The best diagnosis is probably via the [about:sync](https://addons.mozilla.org/en-US/firefox/addon/about-sync/) addon - on any desktop machine, you can see which tabs are open on each individual device - that will help you work out if the problem is that one of the devices is not correctly syncing the tabs which are actually open, or in the front-end code of one of the devices where the list isn't accurately reflecting what about:sync tells you the device is reporting.

**Comment by mhammond** [comment]
I can reproduce some oddness here. Can you please clarify what you mean by "(3) On the first device delete all open tabs" in the initial STR, as deleting all open tabs will typically close the browser. The oddness I can reproduce is if you press the "home" button on the last tab, then the last opened tab does remain syncing.

**Comment by rocketsroger** [comment]
> I can reproduce some oddness here. Can you please clarify what you mean by "(3) On the first device delete all open tabs" in the initial STR, as deleting all open tabs will typically close the browser. The oddness I can reproduce is if you press the "home" button on the last tab, then the last opened tab does remain syncing.

I'm not sure how the originator of this issue reproduced it.  What I did was to have 2-3 tabs open and close Firefox Nightly (desktop) directly by tapping the top left (OSX) x button.  After about 5 mins I check the other Firefox Nightly (desktop) and still see that those tabs are shown as opened on my OSX device.

**Comment by mhammond** [comment]
> What I did was to have 2-3 tabs open and close Firefox Nightly (desktop) directly by tapping the top left (OSX) x button.

That is intentional - closing the browser intentionally doesn't sync an empty tab list

**Comment by rocketsroger** [comment]
> That is intentional - closing the browser intentionally doesn't sync an empty tab list

I see.  Sorry, I've misunderstood the requirement then.  I was assuming that when we close the browser we update to show that no tabs are opened on that device.  Thanks

**Comment by mhammond** [comment]
Thanks - I'm confident the fix was [bug 1785740](https://bugzilla.mozilla.org/show_bug.cgi?id=1785740) so I'll close this.
