### ISSUE TITLE
[Bug]: [Experiment] [Viewpoint Survey (2022 Dec, Android)] The Viewpoint survey message is not displayed on the Homepage of the Firefox Release 107.2.0 and 106.1.0 versions

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla-mobile/fenix#28093]
### Steps to reproduce

**[Prerequisites]:**
- Have the device’s language set to any of the following: 'de', 'en', 'es', 'fr', 'ja', 'pl', 'pt', 'ru', 'zh'.
- Have the Firefox 107 Release build installed on a device.

**[Steps to reproduce]:**
1. Open the 107.2.0 Release build from the prerequisites.
2. Navigate to the Firefox "Settings" menu.
3. Scroll down to the bottom of the list and tap the "About Firefox" option.
4. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
5. Scroll down to the bottom of the list and tap the "Secret Settings" option.
6. Enable the “Use Nimbus Preview Collection” option and restart the browser.
7. Navigate again to the Firefox "Settings" menu -> "About Firefox" option.
8. Tap the "Firefox Browser" logo 5 times and go back to the "Settings" menu.
9. Scroll down to the bottom of the list and tap the "Nimbus Experiments" option.
10. Tap the "Viewpoint Survey (2022 Dec, Android)" experiment.
11. Tap the “treatment” branch and restart the browser.
12. Observe the Homepage.

### Expected behaviour

- A message that asks the user to complete a survey is displayed on the Homepage. 

### Actual behaviour

- The Survey message is not displayed on the Homepage. 

### Device name

Samsung S9, Oneplus 5

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

107.2.0, 106.1.0 

### Additional information

- The issue is partially reproducible on Firefox Release 103, but in this case, the message has the wrong label displayed on the message.
![Screenshot_20221206-145129](https://user-images.githubusercontent.com/26000308/205949286-69a08a9a-62cc-47d5-87be-797e2c62203c.jpg)

- The issue is NOT reproducible with the Firefox Release 105 version on Android devices.
- The issue is NOT reproducible using Firefox 108 RC on an iOS device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22105)

**Comment by Mugurell** [comment]
Thank you for the report!

Based on the versions in which this was tested it seems like 
- we had a bug in 103 with overlapping values (Nimbus experiment and default experiment in the app)
- the above issue was fixed in 105
- we have a bigger bug in 107 - the message is not shown at all.

@SoftVision-CarmenFat I'm curios if you tested in other releases also. This would help us narrowing the changes in code that could have caused this.

**Comment by Mugurell** [comment]
To continue having different behaviors with each release a local build of Release from the current `main` - 109 is showing the right message for me.

![image](https://user-images.githubusercontent.com/11428869/205961346-d8cabc7c-820a-4d81-a9bc-114b022dfe25.png)

**Comment by SoftVision-CiprianMuresan** [comment]
@topotropic you might need to restart the app a second time in order to see experiments from the preview collection.

**Comment by jhugman** [comment]
For investigation purposes:

This is experiment https://experimenter.services.mozilla.com/nimbus/viewpoint-survey-2022-dec-android

**Comment by SoftVision-CarmenFat** [comment]
- I tested on more Firefox versions today and it seems that the issue is also reproducible on the 106.1.0 build (which I installed from the [repo](https://github.com/mozilla-mobile/fenix/releases/tag/v106.1.0)).

- On the other versions that I tested the experiment, the issue is not reproducible on 102.2.1, 103.2.0 (the button's label is still wrong as described in the Additional Notes of this report), 104.2.0, 105.2.0, and 108.0b6.

- Editing the title and Firefox version to reflect the new finding.

**Comment by Mugurell** [comment]
I've tested the current release (107.2.0) on 4 different devices (multiple times):
- a OnePlus 7T with Android 11
- a Pixel 3 with Android 12 
- a Pixel 7 with Android 13
- a Samsung Note 10 with Android 12.
and on all but the Samsung there were cases in which I did saw the expected survey (for >5 installs in a row) and also cases in which I did not saw the survey but did get the default message. On the Samsung device I did not saw the survey in ~20 tries.

This leads me to believe that there is a bug which maybe affects all versions but we have a too small number of tests to encounter both scenarios.

**Comment by Mugurell** [comment]
Small update that I can reproduce this with local builds also.

**Comment by Mugurell** [comment]
Seems like indeed there are some older which leads to the survey not showing:
1. The most important issue relates to the fact that the survey experiment has 11 messages to show.
Seems like the app will try showing a random one from those 11 plus the default browser message and only at the last moment check the conditions for it.
If the user uses the english locale and the app tries to show `viewpoint-invitation-message-en` then the survey will be visible.
If the user uses the french locale and the app tries to show `viewpoint-invitation-message-en` then the survey will not be visible.
Looks like we have to improve the logic for evaluating messages conditions.
2. (Have to test investigate a bit more) The default message (for the default browser card) is not shown until we have a survey to display. Then the next message to be shown is selected from a pool including the default browser card and so this message can be shown instead of the survey.
I understood that the default message [from `nimbus.fml.yaml`](https://github.com/mozilla-mobile/fenix/blob/73d105bd4e3eaabeccd917a31fc3c401c8e43f40/nimbus.fml.yaml#L168) should not be shown if there are others from Nimbus. But from our testing it's clear it is still considered for showing.
Asking @jhugman to validate that assumption about the default message being overridden by server messages in which case this will need to be fixed also.

There may be other small bugs which we didn't know about since we previously only used one message: the default browser card.
Not the Nimbus survey implies multiple messages on top of the default one from the app so many variables change.

The bug from point 1 would explain why we saw the survey showing or not even on the same device, locale and app version.
That bug would also mean that while we'll be able to fix the bug for v108+ targetting users of old applications will not be reliable: they might see the survey or not. Unsure if this is an acceptable compromise. cc @cpeterso

**Comment by jhugman** [comment]
There are 12 messages, corresponding to 11 viewpoint messages for different languages and one for default browser. At most, only two of them are eligible, depending on the language.

The one with highest priority is shown first, until the user interacts (dismisses or clicks on the message). 

Then the next eligible message should be displayed. So when `USER_EN_SPEAKER`, we should see `viewpoint-invitation-message-en` and then `default-browser` after
a) the 4th app launch, 
b) the viewpoint survey message has been clicked on or dismissed.

**Comment by Mugurell** [comment]
Paired with James and we are confident we saw the issue: A race around the active Nimbus enrolments from https://github.com/mozilla-mobile/fenix/blob/releases_v107.0.0/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L439-L457 which would lead to us [trying to show the message](https://github.com/mozilla-mobile/fenix/blob/20b396e0cd82757e70531253acec25db93f26d9d/app/src/main/java/org/mozilla/fenix/gleanplumb/MessagingFeature.kt#L17) before actually having messages to show (from the [Restore](https://github.com/mozilla-mobile/fenix/blob/releases_v107.0.0/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L457) action).

**Comment by Mugurell** [comment]
Tested more and confirmed the problem, it's cause and an easy solution.
The solution from https://github.com/mozilla-mobile/fenix/issues/28093 looks safe enough to get uplifted to release but unfortunately we can only fix this in the next release (108) and the issue is already resolved for later version with a bigger refactoring which took place in 109.

@cpeterso When should a patch be merged? Now to be available in the next 108 release or after the beta cut to be available in a dot release of 108?

**Comment by jhugman** [comment]
Following pairing, this appears to be a race condition, fixed on `main` by https://github.com/mozilla-mobile/fenix/pull/27650 .

Another PR (https://github.com/mozilla-mobile/fenix/pull/28147 ) is also proposed.

**Comment by jhugman** [comment]
> Maybe we can skip the December survey.

I haven't tested this, but I think the message is shown the second time the home screen is shown in the same session.

**Comment by cpeterso** [comment]
> I asked the Viewpoint team what they would like to do. Maybe we can skip the December survey.

I spoke with Rosanne on the User Research team. She said they will skip the December survey and run the January survey after 109 ships (2023-01-17) with the fix.

> > Maybe we can skip the December survey.
> 
> I haven't tested this, but I think the message is shown the second time the home screen is shown in the same session.

@jhugman I don't know all the details about this bug. Does your comment mean we _don't_ need to skip the December survey? That users will simply see the survey prompt on the second time they visit the home screen instead of the first? Or that the message will cause problems that need to be fixed, even if we don't run the December survey?

**Comment by cpeterso** [comment]
Depending on jhugman's answer, if we don't need to land this fix in 108, we can then close this bug as WONTFIX for 108.

**Comment by Mugurell** [comment]
> @jhugman I don't know all the details about this bug. Does your comment mean we _don't_ need to skip the December survey? That users will simply see the survey prompt on the second time they visit the home screen instead of the first? Or that the message will cause problems that need to be fixed, even if we don't run the December survey?

The bug would affect only the first startup of the app if the user goes directly to the homescreen. We wouldn't load the survey in time to be shown.

If :
- the default browser card is not already showing (user can have Firefox as default or tap to close this message)
- the app is opened to an existing tab or after being opened to homescreen the user navigates to a tab (or any other screens like `Settings`)
- and then navigates to app's homescreen the survey should be shown (because we had time to load the survey while the user navigated to the tab).

@SoftVision-CarmenFat to confirm.

**Comment by SoftVision-CarmenFat** [comment]
- For Firefox 108, I was not able to see the Survey message at the first restart after forcing the enrollment, which would have been the expected behavior. Also, I restarted the browser several times, but the result was the same, the Survey message was not displayed on the Homepage.
- After multiple browser restarts, I navigated to a website and then opened a new tab where the Survey message surfaced and was visible. So, in my case, the Survey message seems to have been dependent on navigating to a website and not on the number of browser restarts.

**Comment by jhugman** [comment]
> Does your comment mean we don't need to skip the December survey? That users will simply see the survey prompt on the second time they visit the home screen instead of the first? Or that the message will cause problems that need to be fixed, even if we don't run the December survey?

As @Mugurell and @SoftVision-CarmenFat allude: if the user goes to the homescreen anytime _after_ the first screen is loaded, then there'll see the message correctly loaded. This _might_ affect the survey itself (for data-science reasons), so it's worth telling the Viewpoint team, but I don't think this bug is reason to cancel December's survey.

**Comment by Mugurell** [comment]
@jhugman An interesting point was raised by @jonalmeida: If the first `Evaluate` (currently in the app) works then with my patch calling `Evaluate` again we would be overcounting the impressions for messages which @Amejia481 that pointed by default has a quite small limit.
Looks like we could also uplift https://github.com/mozilla-mobile/fenix/pull/27650 from 109 to 108 to fix the issue and eliminate the overcounting risk?

**Comment by cpeterso** [comment]
I'm not following all the technical details of this bug. If you need me to ask the Viewpoint survey team to do or change something, please let me know.

**Comment by jhugman** [comment]
@cpeterso ok.

@Mugurell yes, that is a interesting point @jonalmeida .

I think at this stage, I think the right way to fix this would be to uplift #27650 from v109 to v108— or WONTFIX. I'd prefer the former, but understand this might be not be possible/desirable— it's only been baking in nightly for just under 4 weeks.

The consequences of WONTFIX are relatively minor in terms of functionality— the message is shown after startup but not _at_ startup— but will probably will need the Viewpoint team's to be informed.

**Comment by Amejia481** [comment]
> I think at this stage, I think the right way to fix this would be to uplift https://github.com/mozilla-mobile/fenix/pull/27650 from v109 to v108— or WONTFIX. I'd prefer the former, but understand this might be not be possible/desirable— it's only been baking in nightly for just under 4 weeks

Yeah agree, uplifting could be really risky as we could be doing changes to the startup critical path, and as James mentioned the patch hasn't been exposed to large set or users, **the cure could be worse than the disease**.

**Comment by onemahon** [comment]
The preceding conversation is causing some confusion to people who are joining into this conversation late, so just to summarize the situation to eliminate confusion:

There are two potential fixes:

* #27650 is a large PR that would solve this bug, but is too risky to uplift to release.
* Petru proposed a smaller PR, #28147, which at least seems to fix this Viewpoint issue. That could be uplifted if necessary.

It sounds like there is a hunch that this bug is more limited than it seemed at first - that the only incorrect case occurs when a user views the homescreen immediately after app startup.

Additionally, Chris P confirmed with the Viewpoint team that they're OK canceling the December survey and delaying the January one until after release day (~ Jan 17th).

As for the current status: we're trying to determine whether to uplift #28147 to beta (not release) or if we can just let #27650 ride the trains without any uplifts.

**Comment by heres-maria** [comment]
We are unable to reliably view the message right now on Firefox Release versions 103.2.0, 105.0.2, 106.1.0, 107.2.0 and 108.2.0 on Android 13 (Samsung Galaxy A52s), Android 10 (Samsung S9) and Android 11 (OnePlus 6T). One variant of the STR used:

1. Open the app.
2. Navigate to a page.
3. Navigate to the homepage.
4. Close and reopen the app.
5. Repeat steps 2-4 until the default browser message is dismissed.
6. Enable the Debug menu by tapping the Firefox icon from Settings > About Firefox.
7. Change to the Preview collection from Settings > Secret Settings > Use Nimbus Preview Collection (on).
8. Close and reopen the app twice.
9. Navigate to a page.
10. Re-enable the Debug menu.
11. Enroll in the experiment by tapping treatment from Settings > Nimbus Experiments > Viewpoint Survey (2023 Jan, Android). 
12. Close and reopen the app.
13. Navigate to the homepage.
14. Navigate to another page and return to the homepage.

The survey was displayed on Firefox Release 102.2.1, 104.2.0 and RC 109.1.0. One of the devices (Android 10) had the message intermittently be displayed on versions 108.2.0 (3 times) and 107.2.0 (once) out of multiple tries.

**Comment by Mugurell** [comment]
Can confirm that that the survey appears intermittently in the current release - 108.
I've observed that if the default browser message gets shown before the survey then the survey won't be shown anymore, while if we manage to enroll in the survey experiment before the conditions for the default browser message are met then the survey will be shown and the default browser message after it as expected.
Trying to reproduce and investigate in local builds.

**Comment by Mugurell** [comment]
Discussed yesterday about this and the product decision was to only have the survey showing for versions >= 109 which should include the patch from https://github.com/mozilla-mobile/fenix/pull/27650 and with that avoid the current issues.
Chris is to double check with the survey owners this decision.
I understand from https://github.com/mozilla-mobile/fenix/issues/28093#issuecomment-1378691893 that the survey does work as expected on 109 RC so looks like we're ready for the survey launch.

**Comment by cpeterso** [comment]
I notified the Viewpoint survey team about the issue on Fenix versions < 109. They will try to target their survey for only version 109. Since this bug is fixed in 109, I think we can close this issue as fixed.

**Comment by SoftVision-CarmenFat** [comment]
Since the decision to launch the experiment only on 109+ versions was made, we verified that the Survey message is displayed as expected on the RC 109.1.0 version. The testing was covered in the **"[QA-1730](https://mozilla-hub.atlassian.net/browse/QA-1730) - Jan 2023 QA Viewpoint Localized Survey on Android and iOS"** request.

Environment:
- Firefox RC 109.1.0 (Build #2015926579), 7d00fc7+ AC: 109.1.0, 5294c37a47 GV: 109.0-20230109151414 AS: 96.1.3 
- Android 9 (Samsung Galaxy S8) (en-US, pt-BR, zh-CN), 
- Android 11 (Google Pixel 2XL) (fr-FR, de-DE, ja-JA, ru-RU), 
- Android 10 (Samsung Galaxy S9) (pt-PT, pl-PL), 
- Android 13 (Samsung Galaxy A52s) (zh-TW)
