### ISSUE TITLE
Auto launch apps with intents

### ISSUE THREAD

**Issue by Lululalu** [mozilla-mobile/fenix#3321]
## Steps to reproduce
Install the Wikipedia app
Search some Wikipedia article on a search engine
Touch the Wikipedia link in the search results page. 

### Expected behavior
Fenix opens the Wikipedia article using the Wikipedia app instead of loading the article page in the browser itself. 

### Actual behavior
It does both. The Wikipedia app opens, but Fenix also loads the Wikipedia page.

### Device information
* Android device: Galaxy A5 2017 8.0 
* Fenix version: 1.0.1923

**Comment by nahuhh** [comment]
Also reported here
https://github.com/webcompat/web-bugs/issues/32741

**Comment by sblatz** [comment]
I believe this was fixed by https://github.com/mozilla-mobile/fenix/pull/4101.

Can QA please verify?

**Comment by kbrosnan** [comment]
I have not been able to get #4101 to show anything in the quick action bar for Wikipedia when the app is installed.

**Comment by sblatz** [comment]
@kbrosnan it should be in the latest nightly now. I am able to get the "open in app" link to show when I have wikipedia installed, then selected wikipedia launches the app with the given article.

**Comment by kbrosnan** [comment]
Started working over the weekend. I don't know why it was not working before. I was using a build that had the pr.

This specific issue is not fixed. It is asking for auto-opening of apps. We currently have manual a request.

**Comment by sblatz** [comment]
If we want to auto open apps, this would be a feature request. Labeling it as such.

That being said, my understanding was we wanted to avoid doing this for security reasons (and because other users have requested that apps not force open from Fenix). I think there are mixed opinions on this request.

**Comment by nahuhh** [comment]
This may NOW be a feature request but at the time it was posted this was already a feature. The "bug" label was because it was a "bug" . Fenix was performing BOTH actions, loading in fenix and at the same time, launching/prompting to launch the associated app. 

 
I am one of the other users who have requested the apps not open automatically -not due to security but because it breaks web browsing - certain links are not meant to be loaded twice. 

I requested section within fenix where you can set default apps.

**Comment by IndefiniteBen** [comment]
I believe default app link handling for intents is handled in the Android system settings, not in the app settings (at least it is on Q).

**Comment by vesta0** [comment]
We chose not to auto launch apps for security reasons as mentioned above, as well as respecting the user choice to open a link in Fenix vs launch an app. The current implementation addresses both. Closing for now but please feel free to re-open if new information surfaces.

**Comment by nahuhh** [comment]
Focus and fenix are both on opposite spectrums. Both implementations on their own are bad. 

I've attached videos of an app intent being used in both fenix and focus, using Google maps. 

In focus when you tap on "directions" a pop-up opens that allows you to open the link in Google maps (full version)

In fenix when you tap on "directions" you are brought to the Google maps mobile website. Then you must use the "open in app" button (which opens in Google maps go)

Ideally
You should tap "directions" and fenix/focus (not android) should show a list of apps that can handle the intent and (fenix/focus) should offer to "don't ask again/remember choice" 
#3349

**Comment by nahuhh** [comment]
Focus:
![20190730_130256](https://user-images.githubusercontent.com/50635951/62149919-d056d400-b2ca-11e9-88ae-c781b8b13aa9.gif)

Fenix:
![20190730_125859](https://user-images.githubusercontent.com/50635951/62149960-e06eb380-b2ca-11e9-9f66-cb71deacf4a5.gif)

**Comment by IndefiniteBen** [comment]
The problem I have is that when I'm reading an article in browser and they have a link to a tweet, which I want to interact with in the app. The way I currently do this is to share to another browser that will just open the twitter app. I don't get a pop-up to 'open in twitter' and when I've seen pop-ups that say "Open in play store" (for example), nothing happens when I tap it.

I can't say what the best implementation is, but the current one is frequently irritating and forcing me into another browser when I want to only use Fenix.
