### ISSUE TITLE
[Bug] Hidden redirect duplicates sync on desktop

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#3526]
## Steps to reproduce
1. On Fenix, go to youtube.com or maps.google.com
1. Sync with desktop.
1. Check the history on desktop.
    1. Expected behavior
Hidden redirects from mobile don't show up in the synced history.
    1. Actual behavior
Hidden redirects from mobile show up in the synced history.
https://www.screencast.com/t/U27zbQxzrf
    1. Device information

* Android device: Note 8 (Android 9)
* Desktop: FF 67.0.2 64 bit, Win 10
* Fenix version: 1.0.0 RC 1

**Comment by vesta0** [comment]
I believe redirects show in Fenix history and there is an A-C bug for it.

**Comment by thomcc** [comment]
I think this is expected behavior. We'll sync redirects from desktop to desktop, I'm not sure why we wouldn't for mobile to desktop. Unless they aren't coming through as redirects?

CC @mhammond, who might have some thoughts.

**Comment by jdragojevic** [comment]
[a-s PR 1715](https://github.com/mozilla/application-services/pull/1715)  Exclude hidden URLs from syncing and views and
[a-c PR 4268](https://github.com/mozilla-mobile/android-components/pull/4268) Pass redirect source and target flags to history tracking delegates should resolve this.

cc @linacambridge @bifleming @vesta0

**Comment by bifleming** [comment]
Please see this doc, and re-test.
\https://docs.google.com/document/d/1er0UfQBp6ylnqqyjP4Ijr7nbh6abivDdf-axhTznZMM/edit#heading=h.mcz1okt1g7yr

**Comment by sv-ohorvath** [comment]
@linacambridge I'm still seeing the redirect sources and middle-links on desktop and the ones synced from Fenix. They are not visible on Fenix:
![Screenshot_20191022-141601](https://user-images.githubusercontent.com/4037709/67281486-2f964000-f4d8-11e9-8e74-8f75de95426f.png)
![desktop_history](https://user-images.githubusercontent.com/4037709/67281958-396c7300-f4d9-11e9-95a6-4fadb1a25188.png)

**Comment by liuche** [comment]
@linacambridge what do you think the next steps here are? (The bot moved this issue into the sprint backlog but it's not really actionable by the Fenix team, I think.)

Will you be working on this, and will it have to go from AS->AC->Fenix?

**Comment by liuche** [comment]
Fenix hides these redirects, but it sounds like maybe they shouldn't even be added to history?

**Comment by liuche** [comment]
This is a question for @grigoryk for the AC/AS parts:
- Is it a bug that hidden redirects get written to History?
- What work would there be to fix this? (Is there a bug?)

**Comment by softvision-miralobontiu** [comment]
This is still reproducible on 2/25 Nightly build with Google Pixel (Android 10).
