### ISSUE TITLE
[Bug] Sometimes the number of tabs on the tab pile button is not centered

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#5346]
## Steps to reproduce
I haven't find a pattern, but it happens quite often

### Expected behavior
The number of tabs is centered in the button

### Actual behavior
The number is on the top right corner of the button.
By the way, maybe it's another bug, but is the space between the shield icon and the lock icon not too wide?

![image](https://user-images.githubusercontent.com/218971/64927171-7755e780-d807-11e9-8393-a2fd7c78ee7b.png)

### Device information
* Android device: Redmi Note 7
* Fenix version: 12580614

**Comment by ekager** [comment]
@mcomella mentioned in a dupe (#5868) that he also sees this and could be related to device font size set to "Large"

**Comment by cadeyrn** [comment]
I don't see this very often but two times in the last few weeks. My device font is not set to "Large".

**Comment by darkwing** [comment]
I haven't seen this in my time working on Fenix.  I did check this out with a hundred tabs open and get this, which looks nice:

![Screenshot_20200211-162618-1](https://user-images.githubusercontent.com/46655/74257680-ca4ea080-4cba-11ea-8b99-a861fce286b7.png)

I'm seeing the textSize set to `12sp` as well as `android:layout_gravity="center"`, so I'm not sure what could be causing this.

**Comment by abodea** [comment]
Verified as fixed with latest Nightly 2/14 with Google Pixel XL(Android 10), Samsung Galaxy S10+(Android 9), Samsung Galaxy S8+(Android 8), Samsung Galaxy S7(Android 7), OnePlus (Android 6), LG K4 (Android 5).

Now...depending on the device screen size this would adjust.
I also tried with 1k tabs opened and the tab number position was correct.

@darkwing @ekager I will keep looking after this while testing and add new info if it will be the case.
Please try to review this and let me know if this verification looks good.

 - Android 10, 9, 8
![Screenshot_20200216-001935](https://user-images.githubusercontent.com/42831109/74544844-7c52ca80-4f50-11ea-9609-0ca67a10bd9e.png)

- Android 7 
![Screenshot_20200214-163354](https://user-images.githubusercontent.com/42831109/74544877-8d9bd700-4f50-11ea-91a6-85244906980a.png)

- Android 6 
![Screenshot_20200214-162813](https://user-images.githubusercontent.com/42831109/74544886-92608b00-4f50-11ea-803c-f9900746a0cf.png)

- Android 5 
![Screenshot_2020-02-14-16-31-56](https://user-images.githubusercontent.com/42831109/74544893-97253f00-4f50-11ea-94e0-f8beece10484.png)

Based on my comment I will close this issue.

**Comment by mcomella** [comment]
I don't see any commits that landed to address this issue: are we sure this is fixed?

> I haven't seen this in my time working on Fenix

I'm pretty sure I've seen this during the time that darkwing has been working on Fenix. Perhaps it's related to my configuration? I have my device font size set to the non-default large.

**Comment by mcomella** [comment]
I saw this today in Nightly 200220 with 11 tabs open and no special STR: reopening.

**Comment by abodea** [comment]
After the `Open Tabs` icon was changed, the border is now correctly displayed and I verified https://github.com/mozilla-mobile/fenix/issues/8505 as the new border is correctly displayed.
Also, note that I was able to find STR:
1. Open a website 
2. Tap on the tab counter button(redirected to home screen)
3. Open a different website 

Note that I was not able to reproduce it all the time.
![Screenshot_20200227-161555](https://user-images.githubusercontent.com/42831109/75456367-1c621800-5983-11ea-8076-f14a29d5a400.png)
![Screenshot_20200227-160933 (1)](https://user-images.githubusercontent.com/42831109/75456388-21bf6280-5983-11ea-87c3-3d18c80b6a4b.png)

**Comment by madb1lly** [comment]
Still have this bug on my Nokia 8, Android 9, fenix 
Nightly 200229 06:01 (Build #2015725811)
35.0.0, 7be369584
GV: 75.0a1-20200228092428
![Screenshot_1582994278076](https://user-images.githubusercontent.com/25123631/75611378-4ef24900-5b1a-11ea-9e7d-549597662cb6.jpg)
It happens the first time I open a new tab from an app, e.g. from fenix homepage, or from k9 mail. Next time I open a tab the number is back in the middle, but if I switch to another app the next time I open a new tab the number will be offset.

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly from 3/3 with Samsung Galaxy S10+ (A 9).
Note that I opened more than 200 pages. Everything worked as expected and the number of the tabs was displayed correctly.
