### ISSUE TITLE
[Bug] Crash when downloading Image

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#6439]
We're getting this new relatively frequent crash: 
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6580864/

```
java.lang.IllegalArgumentException: Failed to find configured root that contains ...
    at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:15)
    at mozilla.components.feature.prompts.MimeType$Image$1.invoke(MimeType.kt:2)
    at mozilla.components.feature.prompts.MimeType$Image.buildIntent(MimeType.kt:5)
    at mozilla.components.feature.prompts.FilePicker.handleFileRequest(FilePicker.kt:19)
    at mozilla.components.feature.prompts.PromptFeature.onPromptRequested$feature_prompts_release(PromptFeature.kt:4)
    at mozilla.components.feature.prompts.PromptFeature$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:7)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:15)
    at mozilla.components.feature.prompts.PromptFeature$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:5)
```

**Comment by sblatz** [comment]
This **may** be fixed in the newest version of AC, but we haven't gotten new snapshot for Fenix, so maybe it's just because we haven't gotten a new snapshot.

**Comment by cpeterso** [comment]
Corresponding GV crash bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1595804

**Comment by sblatz** [comment]
Let's keep a pulse on this over the next few days but it seems to have disappeared?

**Comment by Amejia481** [comment]
I think the issue is still there, the issue happens when the input have an image mime type .

STR:

1. Go https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
2. Toggle Desktop site (to be set **ON**).
3. Tap browser button below the label "**Choose a profile picture**".

I'm taking a look to how to fix it. I will keep you update.

**Comment by Amejia481** [comment]
I think the main issue rely on feature-prompts and Fenix providers has the same `authorities` properties: `android:authorities="${applicationId}.fileprovider"`

**Feature prompts**
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/prompts/src/main/AndroidManifest.xml

```xml
        <provider
            android:authorities="${applicationId}.fileprovider"
            android:name="androidx.core.content.FileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
```

**Fenix**
https://github.com/mozilla-mobile/fenix/blob/7173bdf0b16d0ee7d7956766193bd30e7fbd425c/app/src/main/AndroidManifest.xml#L252

```xml
        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>
```

**Comment by Amejia481** [comment]
Found the source of the issue the `android:name="androidx.core.content.FileProvider"` property is the same is both case and it should be unique.

**Comment by Amejia481** [comment]
This will fix after https://github.com/mozilla-mobile/fenix/pull/6699 lands

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly 11/25 (#13290608) with Google Pixel 3 (Android Q), and Huawei P9 Lite (Android 7).
