### ISSUE TITLE
[Bug] History/Bookmarks sometimes do not sync

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#6713]
## Steps to reproduce
1. Sign in with valid credentials on both desktop and a mobile device.
2. Make sure to browse unique pages in both desktop and mobile, different ones.
3. Trigger sync.
4. Verify if the History synced.

### Expected behavior
The history synced.

### Actual behavior
None of the browsed pages on the desktop are displayed in the history of the mobile device, and vice-versa. I signed out, then resigned in and no changes.

### Device information
* Android device: Nexus 9 (Android 7.1.1), Samsung Galaxy Note 8 (Android 9), and desktop Windows 10
* Fenix version: Nightly 191120 (#13240608)

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3868510/logcat.txt)

**Desktop**:
![desktop](https://user-images.githubusercontent.com/40694158/69228666-a59bce80-0b8c-11ea-8028-a7f897195636.png)

**Tablet**:
![tablet](https://user-images.githubusercontent.com/40694158/69228691-adf40980-0b8c-11ea-9b2b-0c36d0b03d6d.png)

**Comment by vesta0** [comment]
@softvision-miralobontiu please let us know if this is still a bug.

**Comment by softvision-miralobontiu** [comment]
Hi @vesta0!
I am still able to reproduce the issue.
Some history entries from desktop aren't visible at all on mobile devices. I've triggered sync multiple times. Only after signing out, and re-signing in on both desktop and mobile, the history synced fine.
Tested with Nexus 9 (Android 7.1.1), Samsung Galaxy Note 8 (Android 9), Google Pixel (Android Q), and desktop Windows 10.

**Comment by boek** [comment]
@grigoryk ^^

**Comment by Diana-Rus** [comment]
Hi, i can also reproduce the issue with Google Pixel 3 XL (Android 9) on Beta 4.3.0-beta.1

**Comment by grigoryk** [comment]
@softvision-miralobontiu @Diana-Rus is it possible to get a logcat which covers a few mobile syncs using a recent build?

I've read the one attached in https://github.com/mozilla-mobile/fenix/issues/6713#issue-525695950 and it's saying that during every sync, only a single engine was synced (passwords). However, that logcat is from November, and a lot of things changed since then, so it'll be great to see a recent one.

In the meantime, I'll try to reproduce this locally.

**Comment by grigoryk** [comment]
Another question, @softvision-miralobontiu @Diana-Rus  - are you certain that you've performed a sync on Desktop before attempting to sync on Fenix?

While trying to reproduce this locally, I almost thought I did before realizing that Desktop sync just didn't run yet, or ran after I've synced Fenix. So far, keeping this in mind, I don't see any history from Desktop not appearing on Fenix.

**Comment by softvision-miralobontiu** [comment]
Hi @grigoryk,
I could reproduce again the situation, history doesn't sync entirely.

**STR:**
1. I've signed in on desktop - Windows 10.
2. I've signed in with the same account on Google Pixel (Android 10) - sync started automatically on this device.
3. I've signed in with the same account on Sony Xperia Z5 Premium (Android 7.1.1) - - sync started automatically on this device.
4. On desktop, I've opened a unique page.
5. On mobile, I've opened some pages.
6. Triggered manually sync on the two devices and on desktop.
7. On desktop I had 19 entries on History today, but on both mobiles had only 14 entries.
8. Deleted some entries from desktop, and from Sony device.
9. Forced sync manually on all devices again.
10. On both mobile devices, I have the exact same pages as history entries, on desktop I have different entries. 

Please see the attached logcat, maybe it helps.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/4516229/logcat.txt)

Please let us know if there is anything else we can do.

**Device information**
Android devices: Sony Xperia Z5 Premium (Android 7.1.1), Google Pixel (Android 10), and desktop Windows 10
Fenix version: Nightly 200422, 
Fennec version: Nightly 77.0a1 (2020-04-22)

**Comment by mhammond** [comment]
Thanks @softvision-miralobontiu - unfortunately that logcat capture doesn't show any evidence of syncing - would it be possible to capture a longer logcat which captures you performing an explicit sync?

Ideally, please capture that after adding new history to your desktop device - then the sync on the mobile device should see the new history.

And to be clear, does the sync work in either direction? Eg, does new history on the mobile device end up on the desktop device? And vice-versa? Or does it seem as though the desktop and mobile devices simply aren't syncing at all? You mention a need to reconnect before sync starts working - at what stage does it then stop working?

Thanks.

**Comment by softvision-miralobontiu** [comment]
Hi Mark @mhammond 
Here are the logcats from the 2 devices I've tested with:
- the Sony logcat: [logcat.txt](https://github.com/mozilla-mobile/fenix/files/4522209/logcat.txt)
- the HTC logcat: [logcatHTC.txt](https://github.com/mozilla-mobile/fenix/files/4522308/logcatHTC.txt)

Scenarios:
- I have deselected Bookmarks and Logins, and let only History selected, triggered sync, and still no perfect sync. Some pages from desktop are synced on mobiles, but not all.
- I have selected all items to sync, but no luck. 


Here are the entries from each device (screenshots), as you can see, cnn.com for example, appears on desktop, but not on the mobile devices:
**desktop**
![desktop](https://user-images.githubusercontent.com/40694158/80097582-33347d80-8574-11ea-9b43-28c24b51fd86.png)

**Sony**
![Sony](https://user-images.githubusercontent.com/40694158/80097586-362f6e00-8574-11ea-865f-1ef1cbb796c5.png)

**HTC**
![HTC](https://user-images.githubusercontent.com/40694158/80097595-392a5e80-8574-11ea-9e49-304194d3f725.png)

**Device information:**
Android devices: Sony Xperia Z5 Premium (Android 7.1.1), HTC 10 (Android 8), and desktop Windows 10
Fenix version: Nightly 200423,
Fennec version: Nightly 77.0a1 (2020-04-22)

Please let me know if there is anything else I can do to help figure this out.
Thanks,

**Comment by bjherbison** [comment]
My history is synced, but changes to bookmarks aren't synced.

Bookmarks are synced between my Linux accounts, but they don't go to my phone, even after multiple syncs over a couple days. logcat showed Fenix didn't appear to be trying to sync bookmarks. The sync bookmarks checkbox is checked.

Pixel 4, Android 10, Fenix 4.3.0

**Comment by madb1lly** [comment]
Hi all,

I just checked this and found the same is happening to me. I wanted to recover some lost tabs and have discovered that it looks like Fenix hasn't ever synced history for me, **at least since I started using it daily in early February**. There are huge gaps of several days when I view history on desktop and it's not possible at all that I didn't use Fenix on mobile (logged in to Firefox with history syncing enabled) on those days.

So at the moment it's not syncing history properly, nor is syncing open tabs implemented yet, nor syncing of collections (which AFAIK is the only significant difference from Fennex). Thankfully sending tabs is working, but this is the only way to backup a session on Fenix, which is pretty poor considering this browser is no longer in alpha (now in beta) and more and more people are getting migrated from Fennec and being seriously disappointed.

Sorry for the mini-rant, but I need the team at Mozilla to know that these things are incredibly frustrating. Right now I'm seriously considering going back to Fennec.

Cheers 🙂

**Comment by grigoryk** [comment]
From the logs that I've seen, we are legitimately not syncing history/bookmark engines, sometimes (not yet sure under what conditions).

Two high-level directions to further investigate:
1) in a-c, we could be legitimately telling RustSyncManager to not sync affected engines
2) in a-s, RustSyncManager could be misinterpreting which engines it should sync. Perhaps some bad interaction with other clients via meta/global?

I'll start with (1) first, and will look into (2) after.

**Comment by grigoryk** [comment]
Combing through a-c, I don't see what could be going wrong here.

Our main interaction point with a-s is the `SyncParams` object we pass along to `appservices.SyncManager`.
- we always set `engines = null`, which should mean "sync everything"
- `enabledChanges` is usually set to `null` (e.g. during periodic sync, or when user presses Sync Now), but if user disabled/enabled any of the sync engines in Account Settings, it'll be set to a map <Engine, Boolean> with states for all known engines.

Above behaviour seems correct to me. There's nothing else in a-c that we can do to affect which engines will be synced, so I'm thinking the problem lies somewhere in `appservices.SyncManager`. m/g and `disabledEngines` list is where I'd look first.

cc @mhammond

**Comment by ekager** [comment]
@grigoryk could this be related to https://github.com/mozilla-mobile/android-components/issues/7233 ?

**Comment by grigoryk** [comment]
@ekager possibly, but they could also be two distinct issues... @mhammond what do you think? I can't tell from my vantage point.

**Comment by sv-ohorvath** [comment]
I also had problems in syncing bookmarks & got this sync error log: 
[error-sync-1591859129221.txt](https://github.com/mozilla-mobile/fenix/files/4763165/error-sync-1591859129221.txt)

**Comment by jdragojevic** [comment]
@sv-ohorvath  - there was some suggestion that these issues could be related to  mozilla-mobile/android-components#7233  (emily's question above).  That was fixed and is in the latest nightly - wondering if it would be a good time to try to reproduce again.

**Comment by sv-ohorvath** [comment]
I tried today to reproduce the syncing issue and it didn't, on the latest Nightly (6/23). @softvision-miralobontiu @bjherbison @madb1lly could you also confirm if it's fixed for you?  Thanks!

**Comment by bjherbison** [comment]
I tried Nightly and after I made a bookmark change I synced, and promptly got a crash when I tried to see if the bookmarks had updated. (I clicked "report" when it occurred.) But after it relaunched I found the bookmarks change had moved from Desktop to Fenix Nightly.

But that doesn't mean the bug is fixed-- some profiles have always synced bookmarks. When my Fenix 5.0 gets updated to include this code change I need to check whether that profile starts syncing bookmarks.

**Comment by softvision-miralobontiu** [comment]
I had trouble syncing bookmarks again on the latest Nightly build from 6/24.
I had the same account on two devices, Google Pixel (Android 10), and HTC 10 (Android 8), and Windows 10.
I've triggered sync multiple times, but not all the bookmarks and bookmark folders synced.

![sync 24 june](https://user-images.githubusercontent.com/40694158/85568228-2c8cba00-b63a-11ea-9a96-d2d279db4a7d.png)

**Comment by madb1lly** [comment]
Hi @sv-ohorvath,

History seems to have been syncing fine for a few weeks now. I'm running org.mozilla.fennec_Aurora.

Cheers 🙂

**Comment by jdragojevic** [comment]
Hi - it's a little unclear the state of this bug right now.  Would it be possible for someone who can still reproduce the original issue to please add a fresh set of logs?

**Comment by liuche** [comment]
This has been open for a while, and I'm not seeing any more comments, so will close this for now.
