### ISSUE TITLE
Create generic solution to avoid reintroducing background job crash loops

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#7376]
I can't reproduce this reliably: it depends on the build having a certain type of startup crash. However, the risks are huge – essentially users are forced to uninstall – so we should mitigate.

## Steps to reproduce
- Have a startup crash of a certain type such that background tasks also fail
  - In my local build (I need a clean build), GeckoView failed to load
- Open Firefox Preview once

### Expected behavior
Firefox Preview crashes once

### Actual behavior
Firefox Preview crashes every few minutes and displays a dialog every time. This will prompt users and, given the only way to make it stop is to uninstall, will likely result in many uninstalls.

This is probably due to a background task starting on a regular basis even if it crashes.

### Device information

* Android device: ?
* Fenix version: ?

---

To be explicit, **if this is unfixed, it will be a high risk:** the user will see "Fenix has crashed" dialogs repeatedly, even if they're not using the app. **This may result in many uninstallations.**

Note: If it's the crash reporter restarting itself, it's unlikely we'll get those crashes – the user will probably uninstall and we'll probably never see it.

Some potential solutions, off the top of my head:
- (unsustainable) Audit anything that restarts itself (why are we restarting after a crash anyway?).
- (questionable sustainable) catch Exceptions in background tasks
- (questionable sustainable) Limit the number of times the app can restart itself

fwiw, I found an issue where we seem to be restarting too much after a crash including Gecko: https://github.com/mozilla-mobile/fenix/issues/11439 Which increases the chances of an issue like this

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-14964)

**Comment by liuche** [comment]
Sounds like background tasks that are getting retried (maybe background syncs), but continuing to crash. This is kind of a general problem, but maybe @csadilek you can give some advice here. What are some things that we can do about this? Ideally all background services will have their own backoff, and when we see these crashes the caller can add that, but can we enforce something on the AC/Fenix side?

**Comment by kbrosnan** [comment]
We had a number of common crashes that happened in December. Mike can you get a logcat that shows the crash?

**Comment by mcomella** [comment]
> We had a number of common crashes that happened in December. Mike can you get a logcat that shows the crash?

To be explicit, I'm not reporting a specific crash: I'm reporting a behavior that can happen when there is a startup crash. The behavior is that the system's "Firefox Preview keeps crashing" dialog keeps showing up despite me not interacting with the app.

Logs would help understand why this is happening but unfortunately I can no longer reproduce to get them.

@kbrosnan It looks like this issue has been labelled incorrectly: would you mind updating it?

**Comment by kbrosnan** [comment]
We have code to detect solvable startup crashes. I believe @sblatz added it. 

You hit [bug 1605991](https://bugzilla.mozilla.org/show_bug.cgi?id=1605991). The timing of this bug (Dec 27) lines up with the crash spike of 1605991. It was a bad crash for users with PWAs. It feels like this bug comes down to don't ship with bad GV versions.  Though maybe the dev team has some ideas. 

We have #6529 to smoketest Nightly builds before publishing. Though it would not have helped in this case as PWAs are not part of the smoketest.

**Comment by kbrosnan** [comment]
Group triage to see if there is any engineering work here.

**Comment by boek** [comment]
This crash has been fixed. We will track the feature request with #718

**Comment by mcomella** [comment]
Reopening: this isn't a crash bug. This issue tracks a _side effect_ of startup crashes in background jobs.

**Comment by mcomella** [comment]
@MarcLeclair saw a review on Google Play in [the Firefox Preview channel](https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en_CA):

> I keep getting notifications (when not actively using the app) that it has crashed

It seems that this is still relevant (though I don't think that channel has been updated in a while).

**Comment by mcomella** [comment]
I can confirm this is still an issue: I introduced a start up crash (can't load gecko libs) in a local build 9b1953ea86b19df70de173545e1ec81e1e9d6a80 (with local a-c) and I keep getting a dialog, "Unfortunately, Firefox Preview has stopped."

**Comment by mcomella** [comment]
> I can confirm this is still an issue: I introduced a start up crash (can't load gecko libs) in a local build

Note: I can't reproduce this issue if I intentionally throw an exception at the end of in `Application.onCreate`. Perhaps there's something special about the gecko libs error (native code crash?) that causes the app to restart itself in an unsafe way.

**Comment by mcomella** [comment]
> I can confirm this is still an issue: I introduced a start up crash (can't load gecko libs) in a local build [9b1953e](https://github.com/mozilla-mobile/fenix/commit/9b1953ea86b19df70de173545e1ec81e1e9d6a80) (with local a-c) and I keep getting a dialog, "Unfortunately, Firefox Preview has stopped."

csadilek and I suspect this is https://bugzilla.mozilla.org/show_bug.cgi?id=1658465

We should continue to keep this bug open to create a generic solution to this problem.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812773

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
