### ISSUE TITLE
[Bug] The blue dot notification is not disabled after enable/disable the Reader View

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#7408]
## Steps to reproduce
1. Open Firefox Preview; 
2. Go to www.wikipedia.rog/wiki/Main_Page;
3. Open the 3dot menu;
4. Enable the "Reader View" option;
5. Reopen the 3dot menu and disable the "Reader View" option;

### Expected behavior
A blue dot is presented after on the 3dot menu/Reader view option and disappears after enabling it the Reader view option.

### Actual behavior
The blue dot is not disappearing;

### Device information

Android device: 
- Google Pixel (Android Q);
- Samsung Galaxy Note 8 (Android 9);
- Samsung Galaxy S8 (Android 9);
- LG G7 fit (Android 8.1).

* Fenix version: Firefox Preview Nightly 12/30 6:26 AM

**Comment by sblatz** [comment]
I'm not sure what the intended behavior here is on this one. Looping in UX :)

**Comment by liuche** [comment]
I think this is a known issue, that was decided as a tradeoff. @Baron-Severin might know if there are follow-up issues that should be filed, or duped to/from this one.

Adding some context:

## Topic:
QAB functionality was moved to the browser menu toolbar, but items are not highlighted as shown in mocks due to technical issues.

Plan of action:
1. AC will add support for highlightable/togglable items (AC#5022).
2. AC recently landed support for highlighting the 3 dot menu button (no action needed)
3. The Fenix team will integrate 1 and 2

## UX result: 
The 3 dot menu will always show a highlight whenever Reader Mode, Open in App, or PWA are available.  The individual items will also each have a highlight.

## Open concerns:
- There is currently no way for a user to clear these highlights, which could be annoying to users.
- The menu toolbar has gotten pretty crowded.  UX is looking at moving out the functionality from the former QAB, but there are higher priorities right now.
- Browser menu items are facing a combinatorial explosion, requiring copy/pasted implementations whenever we want to combine two styles (like hightlightable / togglable).  It's not yet clear what should be done about this in the long term.

**Comment by kbrosnan** [comment]
What is the value of a notification that appears almost all the time?

**Comment by Baron-Severin** [comment]
@apbitner do you recall why we're not allowing users to clear highlights of reader mode/open in app/PWA?  I know it came up in our meeting, but I can't remember.

**Comment by djc** [comment]
FWIW, I hate the current take on the blue dots -- they appear a lot of the time, and as someone who never uses Reader View or install to homescreen they're worthless to me. Is there some about:config thing I can use to disable them for now?

**Comment by apbitner** [comment]
The goal of the blue dot was to notify the user whenever a contextual action (Install PWA, Reader View, Open in App) is available for the current webpage, similar to how we used to show a peek of the Quick Action Bar.

We could make the blue dot disappear when the user enables Reader View, but we know not everyone uses that feature. Plus, even if it did disappear, it would reappear on the next webpage that supports Reader View.

The blue dot notification system was meant to be a temporary solution because there were dependencies on removing the QAB so that we could enable a top nav bar. We plan on revisiting it in https://github.com/mozilla-mobile/fenix/issues/6350.

**Comment by lnicola** [comment]
I'm just a user, but I find the notification jarring. It looks exactly like the "what's new" dots in Firefox Desktop, so I assumed it's there to teach me about a new feature that just got implemented (reader mode). I'm totally fine with something like this, but it should go away once I use the feature the first time (or couple of times), or if I ignore it for some time.

If the notification is there to tell me I can enable Reader Mode, I think it's too "loud". Assuming I've used the feature before, I know what it does and I either:

 - don't like it, so the blue dot doesn't offer me much
 - like it, so I know -- because I've used it -- to look in the menu when I want to enable Reader Mode

**Comment by sblatz** [comment]
This seems like something we should address during polish.

**Comment by vesta0** [comment]
We should fix this. Either remove the dot once reader mode is enabled or ideally once the user opens the toolbar (and sees the blue dot) once. 

If this is too technically complex to do, we may need to consider removing the blue dot notification for reader mode all together (keeping it for PWA and open in app) for now. Doing that will hurt feature discoverability, but the current state is irritating/confusing to users and doesn't accomplish its original goal either.

**Comment by apbitner** [comment]
@vesta0 I propose the following:

- The blue dot appears next to the 3-dot icon the first time the user visits a site that supports reader view, open in app, or PWA. This could happen all at once on one page, or over time across multiple supported pages.
- When the user opens the menu, they will still see a blue dot next to the appropriate menu item
- Both blue dots (3-dot icon & menu item) will be dismissed if the user taps on that menu item, OR just closes the menu. I don't think we should force a user to perform an action if they simply want to dismiss the blue dot notification.

This will raise awareness of these features to the user, but not remind them every time they're on a supported page. Thoughts?

**Comment by vesta0** [comment]
@apbitner that sounds like a good short-term solution 👍

**Comment by Baron-Severin** [comment]
@BranescuMihai is working on this in
https://github.com/mozilla-mobile/fenix/pull/8805

**Comment by softvision-miralobontiu** [comment]
Verified on the latest Nightly build from 3/11, and on Beta v4,1,0-beta.1, and:
* on installation, the three-dot menu has the "What's new" highlight blue dot that only goes away if the "What's new" article is opened;
* the blue dot appears next to the three-dot icon the first time the user visits a site that supports reader view or open in-app. Opening the three-dot menu and closing it, makes the highlight disappear, the user doesn't have to perform other activities. Opening a new page that supports reader view, will not display the blue dot highlight again.

Tested on Samsung Galaxy Tab S6 (Android 9), and Xiaomi Mi4i (Android 5.0.2).
