### ISSUE TITLE
[Bug]Broken uBlock link icon to addons.mozilla.org on android 5 & 6 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#8147]
## Prerequisites
uBlock Origin Add-on should be installed.

## Steps to reproduce
1. Open the "Add-ons manager"
2. Tap on uBlock's "Details" section
3. Swipe down until you reach the end of the page
4. Check the "Homepage" link icon

### Expected behavior
The "Homepage" link icon should be properly displayed.

### Actual behavior
Improperly displayed "Homepage" link icon.

### Device information

* Android device: 
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly #20370604 from 2/6

### Notes
► Screenshot Light theme
![rsz_1screenshot_20200206-120205](https://user-images.githubusercontent.com/51314259/73927473-2770dd80-48da-11ea-859b-8055f24b4113.png)

► Screenshot Dark theme
![rsz_screenshot_20200206-120237](https://user-images.githubusercontent.com/51314259/73927550-453e4280-48da-11ea-8a99-156262cf6e24.png)

❗ Not reproducible on the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)

**Comment by AndiAJ** [comment]
+1 from uBlock Origin's permissions section
![rsz_screenshot_20200206-162627](https://user-images.githubusercontent.com/51314259/73945859-a3305180-48fd-11ea-8aa0-dd66eb5ad6cc.png)

**Comment by Amejia481** [comment]
@AndiAJ  this should be fixed, could you please verify?

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly #20380605 from 2/7`** using the following devices:
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

✔️  "Details" section
❌ "Permissions" section

Looks like it's still reproducible in the Permission section.
@ekager - Please review ☺️ 

**I'll remove the QA need label.**

**Comment by ekager** [comment]
Will be fixed by https://github.com/mozilla-mobile/android-components/pull/5852

**Comment by Amejia481** [comment]
@ekager thanks for patch above ❤️  it will fix the issue in sample browser :)
but for addressing the issue on Fenix we have to we have to do the same on [fragment_add_on_permissions.xml](https://github.com/mozilla-mobile/fenix/blob/a896b47cfe7be8fb7039fe692295419e2c5bee9e/app/src/main/res/layout/fragment_add_on_permissions.xml#L27)

**Comment by ekager** [comment]
Hahahaha omg doing that now

**Comment by ekager** [comment]
Correction: https://github.com/mozilla-mobile/fenix/pull/8217 will fix this

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest `**Nightly #20410606 from 2/10** `using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0.0)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)


<details>
    <summary>Screenshots from LG Nexus 4 Light theme (dropdown)</summary>

![rsz_screenshot_2020-02-13-12-55-49](https://user-images.githubusercontent.com/51314259/74137256-22709e80-4bf8-11ea-9572-d29ef550b072.png)
![rsz_screenshot_2020-02-13-12-55-43](https://user-images.githubusercontent.com/51314259/74137182-05d46680-4bf8-11ea-9ad1-bb1453b75e7c.png)

</details>

<details>
    <summary>Screenshots from LG Nexus 4 Dark theme (dropdown)</summary>
   
![rsz_screenshot_2020-02-13-12-56-08](https://user-images.githubusercontent.com/51314259/74137036-cdcd2380-4bf7-11ea-9281-fbf181b58ee7.png)
![rsz_screenshot_2020-02-13-12-56-14](https://user-images.githubusercontent.com/51314259/74137091-e1788a00-4bf7-11ea-88a6-829304e4d916.png)


</details>
