### ISSUE TITLE
[Logins] Text field should be deselected when finish editing login capture

### ISSUE THREAD

**Issue by AmyYLee** [mozilla-mobile/fenix#8548]
Steps to reproduce:

1. Go to a website and put in login credentials 
2. When asked if you want to save the login tap on the username text field to edit login
3. Tap done on on the keyboard when you're finished editing the login

Expected:
1. Keyboard disappears and text field is no longer in edit state

Actual: 
1. Keyboard disappears and text field is still in edit state with text cursor flashing

**Comment by ValentinTimisica** [comment]
I filed an [issue](https://github.com/mozilla-mobile/android-components/issues/6295) in A-C and created a PR. Should be fixed by https://github.com/mozilla-mobile/android-components/pull/6296.

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on the latest **`Nightly Build #20970607 from 4/6`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

It seems to be **working after editing the user name** (**all devices**), on the other hand **after editing the password** on both the Samsung S6 and OnePlus A3 **it takes two keyboard confirmations to exit the edit state**.

► Video from OnePlus A3
![20200406-113353](https://user-images.githubusercontent.com/51314259/78539940-09512c00-77fc-11ea-9204-4c3a7d2e197f.gif)


@ValentinTimisica - Please review and share your thoughts. ☺️ 
I'll remove the QA needed label until further notice.

**Comment by AndiAJ** [comment]
Hi, I've re-checked this matter on the latest **`Nightly Build #21060608 from 4/15`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

✔️ Works properly on both Google Pixel 3a & Huawei Mate 20 Lite 
❌ Unfortunately, the problem is still reproducible on Samsung Galaxy S6 &  OnePlus A3

► Video from OnePlus A3
![20200415-174301-1](https://user-images.githubusercontent.com/51314259/79352176-2eebdd00-7f42-11ea-8165-a06a951d1576.gif)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build #21070609 from 4/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• Samsung Galaxy S6 (Android 7)
• OnePlus A3 (Android 6.0.1)

► Video from OnePlus A3
![20200416-122621](https://user-images.githubusercontent.com/51314259/79440099-45477680-7fde-11ea-8792-4485b6ed9c93.gif)
