### ISSUE TITLE
[Telemetry] Save Logins Prompt

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/fenix#9730]
#### Description & Product Manager / Data Scientist User Story
- As a product manager, I want to know how many users are actually saving logins in Fenix. This will help me prioritize Login related bugs and enhancements. It will also help me understand how users feel about this feature and whether they find the prompts useful or intrusive. 

#### What questions will you answer with this data?
- How many users choose to save logins in the browser?
- How many logins do users save on average?
- How often users see the login prompt but choose to NOT save a login. 

#### What probes (suggested, if applicable)
- An event that’s fired when the save login prompt is displayed
- An event that's fired when a login is saved

### Acceptance Criteria
- Initial sign-off by DS to ensure instrumentation will address product questions. 
- Event pings can be queried via re:dash
- Event pings can be queried via amplitude
- We are sending telemetry events for the actions listed in the requirements
- We have documented the telemetry
- We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

**Comment by vesta0** [comment]
Dev proposal goes [here](https://docs.google.com/document/d/1hVtSd8gDV1AtzxjhYlKiKYZpGxXDu6SdBNsaBQ5Lodc/edit#)

**Comment by sblatz** [comment]
@vesta0 can I get access to that google doc link so I can start this? :)

**Comment by vesta0** [comment]
Sorry, you have access to the [doc ](https://docs.google.com/document/d/1hVtSd8gDV1AtzxjhYlKiKYZpGxXDu6SdBNsaBQ5Lodc/edit#)now :)

Please include the Dev proposal in this [JIRA ticket](https://jira.mozilla.com/browse/DS-579) for DS review :)

**Comment by sblatz** [comment]
Updated the Jira ticket with the dev proposal!

**Comment by AndiAJ** [comment]
Hi @sblatz , I've just checked this matter on both the latest **`Nightly Build 200730`** and **`Fenix Beta 80.0.0-beta-1`** using a Google Pixel 3a (Android 10)

✔️ **The login dialog prompt was displayed**
Nightly - Ping 92ca4883-f08f-4f30-b00e-9d7f22c025c1
Beta - Ping ed28dde9-5847-4152-a4a2-9c745ef92100

```
 {
          "category": "login_dialog",
          "name": "displayed"
```

✔️ **The login dialog prompt was cancelled**
Nightly - Ping 124cc402-59bf-4061-9b2b-9a69232cea6d
Beta - Ping e18da1e1-6b43-4678-875d-731820fb80f8

```
"events": [
        {
          "category": "login_dialog",
          "name": "cancelled"
```

✔️  **The login dialog prompt "save" button was pressed** 
Nightly - Ping b450243e-5484-4836-81ed-90b4ab1fbd18
Beta - Ping a9ec36cd-4d1b-4c45-b79f-f70e15345455

```
{
          "category": "login_dialog",
          "name": "saved"
```

✔️ **The login dialog prompt "never save" button was pressed** 
Nightly - Ping 6713b09f-6312-4e27-bbbc-842e6bdf40ce
Beta - Ping 654f54a6-39c1-4e7e-908a-2fd20c2e1f5c

```
{
          "category": "login_dialog",
          "name": "never_save"
```

✔️ **The login dialog prompt "update" button was pressed** 
Nightly - Ping a5d62fdd-8cb6-4ceb-b8ed-5c6371888d4a
Beta - Ping 80423eae-bc03-4a17-899b-8161df89e459
```
{
          "category": "login_dialog",
          "name": "saved"

```

✔️ **The login dialog prompt "Don't update" button was pressed** 
Nightly - ❌ 
Beta -  d83446ce-7f81-43b9-b396-048c056cdbef
```
{
          "category": "login_dialog",
          "name": "never_save"
```

[Nightly Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t3007003)
[Beta Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t3007002)
[Nightly Logcat](https://github.com/mozilla-mobile/fenix/files/5001952/loginN.txt)
[Beta Logcat](https://github.com/mozilla-mobile/fenix/files/5001953/logB.txt)

❓ Quite odd that after pressing the "Don't update" button nothing get's generated on Nightly
Please review and share your thoughts. ☺️

**Comment by sblatz** [comment]
@AndiAJ Thanks for checking this! The "Don't update" button is not tracked. In the beta build there was a bug where it was reported as "never save" but has been fixed in the nightly build to just not send an event :)

**Comment by AndiAJ** [comment]
Hey @sblatz , thanks for the heads up. ☺️ 
One more thing, for the update button is it ok to track the event as **`"name": "saved"`** ? shouldn't it be something like **`"name": "update"`** ?

It seems that the "Don't update" button still get's tracked on **`80.0.0-beta.2`**, @liuche how should I proceed?

**Comment by ekager** [comment]
@vesta0 do you want us to split out "update" login events from new "save" login events? Do you also care about "don't update" events (we could probably also track these under "cancel")

**Comment by vesta0** [comment]
Hey @ekager, great question. I don't think we need to track "update" at this time. I rather lean on the side of collecting only the data that we need.

**Comment by vesta0** [comment]
I believe this is done.
