### ISSUE TITLE
[Bug]Can't shrink the collections

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#9914]
## Prerequisites
Have a collection created.

## Steps to reproduce
1. Tap on the right side of the previously created collection
2. Tap on the share button
3. Tap somewhere next to the share button
4. Tap on the space between the Collections name and share button
5. Tap on the collections name or on the expand/shrink sign

### Expected behavior
At Step 3 the share button shouldn't be pressed.
At Step 5 the collection should shrink 

### Actual behavior
At Step 3 performing a tap next to the share button opens the share screen
At step 5 can't shrink the collection

### Device information

* Android device: nePlus A3 (Android 6.0.1)
* Fenix version: 
• Fenix beta 4.3.0-beta.1 (Build #21050021)
• Debug build from Master 4/14

### Notes
► Video
![20200414-151621](https://user-images.githubusercontent.com/51314259/79226642-620d6e00-7e67-11ea-9cad-c3dc211d9892.gif)

❗ Seems to be happening when performing actions on the hidden collections buttons. 
Similar with #9913

**Comment by mcarare** [comment]
Should be fixed when https://github.com/mozilla-mobile/fenix/pull/10144/commits/cf847c46f8b1a1c2db7fb4bd9d3a17fa05f30b4b lands.

**Comment by Diana-Rus** [comment]
Hi, the issue has been reproduced on a Firefox Preview Nightly 4/23 and verified as fixed on Firefox Preview Nightly 4/27 with Sony Xperia Z5 (Android 7) and Google Pixel 3 XL (Android 9), but with Samsung Galaxy S9 (Android 8) I can still reproduce the issue - please check GIF

Sony Xperia Z5 - GIF - ✔️
![20200427-111308](https://user-images.githubusercontent.com/49859863/80352381-7a748400-887c-11ea-83d2-704a005ab547.gif)

Pixel 3 XL - GIF - ✔️
![20200427-112625](https://user-images.githubusercontent.com/49859863/80352625-d212ef80-887c-11ea-87fc-8d9a89bd9b41.gif)

Samsung Galaxy S9 - GIF - ❌
![20200427-115602](https://user-images.githubusercontent.com/49859863/80353890-ae50a900-887e-11ea-882b-e0b538044d02.gif)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 4/28** with **Google Pixel 4 XL (10), Samsung Galaxy S9 (9).**
